/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.umn.gis.mapscript;

public class CompositingFilter {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CompositingFilter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CompositingFilter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mapscriptJNI.delete_CompositingFilter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFilter(String value) {
    mapscriptJNI.CompositingFilter_filter_set(swigCPtr, this, value);
  }

  public String getFilter() {
    return mapscriptJNI.CompositingFilter_filter_get(swigCPtr, this);
  }

  public void setNext(CompositingFilter value) {
    mapscriptJNI.CompositingFilter_next_set(swigCPtr, this, CompositingFilter.getCPtr(value), value);
  }

  public CompositingFilter getNext() {
    long cPtr = mapscriptJNI.CompositingFilter_next_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CompositingFilter(cPtr, false);
  }

  public CompositingFilter() {
    this(mapscriptJNI.new_CompositingFilter(), true);
  }

}
