/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.umn.gis.mapscript;

public class DBFInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DBFInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DBFInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mapscriptJNI.delete_DBFInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int getNRecords() {
    return mapscriptJNI.DBFInfo_nRecords_get(swigCPtr, this);
  }

  public int getNFields() {
    return mapscriptJNI.DBFInfo_nFields_get(swigCPtr, this);
  }

  public String getFieldName(int iField) {
    return mapscriptJNI.DBFInfo_getFieldName(swigCPtr, this, iField);
  }

  public int getFieldWidth(int iField) {
    return mapscriptJNI.DBFInfo_getFieldWidth(swigCPtr, this, iField);
  }

  public int getFieldDecimals(int iField) {
    return mapscriptJNI.DBFInfo_getFieldDecimals(swigCPtr, this, iField);
  }

  public int getFieldType(int iField) {
    return mapscriptJNI.DBFInfo_getFieldType(swigCPtr, this, iField);
  }

  public DBFInfo() {
    this(mapscriptJNI.new_DBFInfo(), true);
  }

}
