/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.umn.gis.mapscript;

public final class debugLevel {
  public final static debugLevel MS_DEBUGLEVEL_ERRORSONLY = new debugLevel("MS_DEBUGLEVEL_ERRORSONLY", mapscriptJNI.MS_DEBUGLEVEL_ERRORSONLY_get());
  public final static debugLevel MS_DEBUGLEVEL_DEBUG = new debugLevel("MS_DEBUGLEVEL_DEBUG", mapscriptJNI.MS_DEBUGLEVEL_DEBUG_get());
  public final static debugLevel MS_DEBUGLEVEL_TUNING = new debugLevel("MS_DEBUGLEVEL_TUNING", mapscriptJNI.MS_DEBUGLEVEL_TUNING_get());
  public final static debugLevel MS_DEBUGLEVEL_V = new debugLevel("MS_DEBUGLEVEL_V", mapscriptJNI.MS_DEBUGLEVEL_V_get());
  public final static debugLevel MS_DEBUGLEVEL_VV = new debugLevel("MS_DEBUGLEVEL_VV", mapscriptJNI.MS_DEBUGLEVEL_VV_get());
  public final static debugLevel MS_DEBUGLEVEL_VVV = new debugLevel("MS_DEBUGLEVEL_VVV", mapscriptJNI.MS_DEBUGLEVEL_VVV_get());
  public final static debugLevel MS_DEBUGLEVEL_DEVDEBUG = new debugLevel("MS_DEBUGLEVEL_DEVDEBUG", mapscriptJNI.MS_DEBUGLEVEL_DEVDEBUG_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static debugLevel swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + debugLevel.class + " with value " + swigValue);
  }

  private debugLevel(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private debugLevel(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private debugLevel(String swigName, debugLevel swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static debugLevel[] swigValues = { MS_DEBUGLEVEL_ERRORSONLY, MS_DEBUGLEVEL_DEBUG, MS_DEBUGLEVEL_TUNING, MS_DEBUGLEVEL_V, MS_DEBUGLEVEL_VV, MS_DEBUGLEVEL_VVV, MS_DEBUGLEVEL_DEVDEBUG };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

