/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.umn.gis.mapscript;

public class intarray {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected intarray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(intarray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mapscriptJNI.delete_intarray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public intarray(int nelements) {
    this(mapscriptJNI.new_intarray(nelements), true);
  }

  public int getitem(int index) {
    return mapscriptJNI.intarray_getitem(swigCPtr, this, index);
  }

  public void setitem(int index, int value) {
    mapscriptJNI.intarray_setitem(swigCPtr, this, index, value);
  }

  public SWIGTYPE_p_int cast() {
    long cPtr = mapscriptJNI.intarray_cast(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public static intarray frompointer(SWIGTYPE_p_int t) {
    long cPtr = mapscriptJNI.intarray_frompointer(SWIGTYPE_p_int.getCPtr(t));
    return (cPtr == 0) ? null : new intarray(cPtr, false);
  }

}
