/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.umn.gis.mapscript;

public class labelObj {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected labelObj(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(labelObj obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mapscriptJNI.delete_labelObj(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int getRefcount() {
    return mapscriptJNI.labelObj_refcount_get(swigCPtr, this);
  }

  public void setFont(String value) {
    mapscriptJNI.labelObj_font_set(swigCPtr, this, value);
  }

  public String getFont() {
    return mapscriptJNI.labelObj_font_get(swigCPtr, this);
  }

  public void setColor(colorObj value) {
    mapscriptJNI.labelObj_color_set(swigCPtr, this, colorObj.getCPtr(value), value);
  }

  public colorObj getColor() {
    long cPtr = mapscriptJNI.labelObj_color_get(swigCPtr, this);
    return (cPtr == 0) ? null : new colorObj(cPtr, false);
  }

  public void setOutlinecolor(colorObj value) {
    mapscriptJNI.labelObj_outlinecolor_set(swigCPtr, this, colorObj.getCPtr(value), value);
  }

  public colorObj getOutlinecolor() {
    long cPtr = mapscriptJNI.labelObj_outlinecolor_get(swigCPtr, this);
    return (cPtr == 0) ? null : new colorObj(cPtr, false);
  }

  public void setOutlinewidth(int value) {
    mapscriptJNI.labelObj_outlinewidth_set(swigCPtr, this, value);
  }

  public int getOutlinewidth() {
    return mapscriptJNI.labelObj_outlinewidth_get(swigCPtr, this);
  }

  public void setShadowcolor(colorObj value) {
    mapscriptJNI.labelObj_shadowcolor_set(swigCPtr, this, colorObj.getCPtr(value), value);
  }

  public colorObj getShadowcolor() {
    long cPtr = mapscriptJNI.labelObj_shadowcolor_get(swigCPtr, this);
    return (cPtr == 0) ? null : new colorObj(cPtr, false);
  }

  public void setShadowsizex(int value) {
    mapscriptJNI.labelObj_shadowsizex_set(swigCPtr, this, value);
  }

  public int getShadowsizex() {
    return mapscriptJNI.labelObj_shadowsizex_get(swigCPtr, this);
  }

  public void setShadowsizey(int value) {
    mapscriptJNI.labelObj_shadowsizey_set(swigCPtr, this, value);
  }

  public int getShadowsizey() {
    return mapscriptJNI.labelObj_shadowsizey_get(swigCPtr, this);
  }

  public void setSize(int value) {
    mapscriptJNI.labelObj_size_set(swigCPtr, this, value);
  }

  public int getSize() {
    return mapscriptJNI.labelObj_size_get(swigCPtr, this);
  }

  public void setMinsize(int value) {
    mapscriptJNI.labelObj_minsize_set(swigCPtr, this, value);
  }

  public int getMinsize() {
    return mapscriptJNI.labelObj_minsize_get(swigCPtr, this);
  }

  public void setMaxsize(int value) {
    mapscriptJNI.labelObj_maxsize_set(swigCPtr, this, value);
  }

  public int getMaxsize() {
    return mapscriptJNI.labelObj_maxsize_get(swigCPtr, this);
  }

  public void setPosition(int value) {
    mapscriptJNI.labelObj_position_set(swigCPtr, this, value);
  }

  public int getPosition() {
    return mapscriptJNI.labelObj_position_get(swigCPtr, this);
  }

  public void setOffsetx(int value) {
    mapscriptJNI.labelObj_offsetx_set(swigCPtr, this, value);
  }

  public int getOffsetx() {
    return mapscriptJNI.labelObj_offsetx_get(swigCPtr, this);
  }

  public void setOffsety(int value) {
    mapscriptJNI.labelObj_offsety_set(swigCPtr, this, value);
  }

  public int getOffsety() {
    return mapscriptJNI.labelObj_offsety_get(swigCPtr, this);
  }

  public void setAngle(double value) {
    mapscriptJNI.labelObj_angle_set(swigCPtr, this, value);
  }

  public double getAngle() {
    return mapscriptJNI.labelObj_angle_get(swigCPtr, this);
  }

  public void setAnglemode(MS_POSITIONS_ENUM value) {
    mapscriptJNI.labelObj_anglemode_set(swigCPtr, this, value.swigValue());
  }

  public MS_POSITIONS_ENUM getAnglemode() {
    return MS_POSITIONS_ENUM.swigToEnum(mapscriptJNI.labelObj_anglemode_get(swigCPtr, this));
  }

  public void setBuffer(int value) {
    mapscriptJNI.labelObj_buffer_set(swigCPtr, this, value);
  }

  public int getBuffer() {
    return mapscriptJNI.labelObj_buffer_get(swigCPtr, this);
  }

  public void setAlign(int value) {
    mapscriptJNI.labelObj_align_set(swigCPtr, this, value);
  }

  public int getAlign() {
    return mapscriptJNI.labelObj_align_get(swigCPtr, this);
  }

  public void setWrap(char value) {
    mapscriptJNI.labelObj_wrap_set(swigCPtr, this, value);
  }

  public char getWrap() {
    return mapscriptJNI.labelObj_wrap_get(swigCPtr, this);
  }

  public void setMaxlength(int value) {
    mapscriptJNI.labelObj_maxlength_set(swigCPtr, this, value);
  }

  public int getMaxlength() {
    return mapscriptJNI.labelObj_maxlength_get(swigCPtr, this);
  }

  public void setSpace_size_10(double value) {
    mapscriptJNI.labelObj_space_size_10_set(swigCPtr, this, value);
  }

  public double getSpace_size_10() {
    return mapscriptJNI.labelObj_space_size_10_get(swigCPtr, this);
  }

  public void setMinfeaturesize(int value) {
    mapscriptJNI.labelObj_minfeaturesize_set(swigCPtr, this, value);
  }

  public int getMinfeaturesize() {
    return mapscriptJNI.labelObj_minfeaturesize_get(swigCPtr, this);
  }

  public void setAutominfeaturesize(int value) {
    mapscriptJNI.labelObj_autominfeaturesize_set(swigCPtr, this, value);
  }

  public int getAutominfeaturesize() {
    return mapscriptJNI.labelObj_autominfeaturesize_get(swigCPtr, this);
  }

  public void setMinscaledenom(double value) {
    mapscriptJNI.labelObj_minscaledenom_set(swigCPtr, this, value);
  }

  public double getMinscaledenom() {
    return mapscriptJNI.labelObj_minscaledenom_get(swigCPtr, this);
  }

  public void setMaxscaledenom(double value) {
    mapscriptJNI.labelObj_maxscaledenom_set(swigCPtr, this, value);
  }

  public double getMaxscaledenom() {
    return mapscriptJNI.labelObj_maxscaledenom_get(swigCPtr, this);
  }

  public void setMindistance(int value) {
    mapscriptJNI.labelObj_mindistance_set(swigCPtr, this, value);
  }

  public int getMindistance() {
    return mapscriptJNI.labelObj_mindistance_get(swigCPtr, this);
  }

  public void setRepeatdistance(int value) {
    mapscriptJNI.labelObj_repeatdistance_set(swigCPtr, this, value);
  }

  public int getRepeatdistance() {
    return mapscriptJNI.labelObj_repeatdistance_get(swigCPtr, this);
  }

  public void setMaxoverlapangle(double value) {
    mapscriptJNI.labelObj_maxoverlapangle_set(swigCPtr, this, value);
  }

  public double getMaxoverlapangle() {
    return mapscriptJNI.labelObj_maxoverlapangle_get(swigCPtr, this);
  }

  public void setPartials(int value) {
    mapscriptJNI.labelObj_partials_set(swigCPtr, this, value);
  }

  public int getPartials() {
    return mapscriptJNI.labelObj_partials_get(swigCPtr, this);
  }

  public void setForce(int value) {
    mapscriptJNI.labelObj_force_set(swigCPtr, this, value);
  }

  public int getForce() {
    return mapscriptJNI.labelObj_force_get(swigCPtr, this);
  }

  public void setEncoding(String value) {
    mapscriptJNI.labelObj_encoding_set(swigCPtr, this, value);
  }

  public String getEncoding() {
    return mapscriptJNI.labelObj_encoding_get(swigCPtr, this);
  }

  public void setPriority(int value) {
    mapscriptJNI.labelObj_priority_set(swigCPtr, this, value);
  }

  public int getPriority() {
    return mapscriptJNI.labelObj_priority_get(swigCPtr, this);
  }

  public void setNumstyles(int value) {
    mapscriptJNI.labelObj_numstyles_set(swigCPtr, this, value);
  }

  public int getNumstyles() {
    return mapscriptJNI.labelObj_numstyles_get(swigCPtr, this);
  }

  public void setSizeunits(int value) {
    mapscriptJNI.labelObj_sizeunits_set(swigCPtr, this, value);
  }

  public int getSizeunits() {
    return mapscriptJNI.labelObj_sizeunits_get(swigCPtr, this);
  }

  public labelObj() {
    this(mapscriptJNI.new_labelObj(), true);
  }

  public int updateFromString(String snippet) {
    return mapscriptJNI.labelObj_updateFromString(swigCPtr, this, snippet);
  }

  public String convertToString() {
    return mapscriptJNI.labelObj_convertToString(swigCPtr, this);
  }

  public int removeBinding(int binding) {
    return mapscriptJNI.labelObj_removeBinding(swigCPtr, this, binding);
  }

  public String getBinding(int binding) {
    return mapscriptJNI.labelObj_getBinding(swigCPtr, this, binding);
  }

  public int setBinding(int binding, String item) {
    return mapscriptJNI.labelObj_setBinding(swigCPtr, this, binding, item);
  }

  public int setExpression(String expression) {
    return mapscriptJNI.labelObj_setExpression(swigCPtr, this, expression);
  }

  public String getExpressionString() {
    return mapscriptJNI.labelObj_getExpressionString(swigCPtr, this);
  }

  public int setText(String text) {
    return mapscriptJNI.labelObj_setText(swigCPtr, this, text);
  }

  public String getTextString() {
    return mapscriptJNI.labelObj_getTextString(swigCPtr, this);
  }

  public styleObj getStyle(int i) {
    long cPtr = mapscriptJNI.labelObj_getStyle(swigCPtr, this, i);
    return (cPtr == 0) ? null : new styleObj(cPtr, true);
  }

  public int insertStyle(styleObj style, int index) {
    return mapscriptJNI.labelObj_insertStyle(swigCPtr, this, styleObj.getCPtr(style), style, index);
  }

  public styleObj removeStyle(int index) {
    long cPtr = mapscriptJNI.labelObj_removeStyle(swigCPtr, this, index);
    return (cPtr == 0) ? null : new styleObj(cPtr, true);
  }

  public int moveStyleUp(int index) {
    return mapscriptJNI.labelObj_moveStyleUp(swigCPtr, this, index);
  }

  public int moveStyleDown(int index) {
    return mapscriptJNI.labelObj_moveStyleDown(swigCPtr, this, index);
  }

}
