/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.umn.gis.mapscript;

public final class MS_CONFIG_SECTIONS {
  public final static MS_CONFIG_SECTIONS MS_CONFIG_SECTION = new MS_CONFIG_SECTIONS("MS_CONFIG_SECTION", mapscriptJNI.MS_CONFIG_SECTION_get());
  public final static MS_CONFIG_SECTIONS MS_CONFIG_SECTION_ENV = new MS_CONFIG_SECTIONS("MS_CONFIG_SECTION_ENV");
  public final static MS_CONFIG_SECTIONS MS_CONFIG_SECTION_MAPS = new MS_CONFIG_SECTIONS("MS_CONFIG_SECTION_MAPS");
  public final static MS_CONFIG_SECTIONS MS_CONFIG_SECTION_PLUGINS = new MS_CONFIG_SECTIONS("MS_CONFIG_SECTION_PLUGINS");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static MS_CONFIG_SECTIONS swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + MS_CONFIG_SECTIONS.class + " with value " + swigValue);
  }

  private MS_CONFIG_SECTIONS(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private MS_CONFIG_SECTIONS(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private MS_CONFIG_SECTIONS(String swigName, MS_CONFIG_SECTIONS swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static MS_CONFIG_SECTIONS[] swigValues = { MS_CONFIG_SECTION, MS_CONFIG_SECTION_ENV, MS_CONFIG_SECTION_MAPS, MS_CONFIG_SECTION_PLUGINS };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

