/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.umn.gis.mapscript;

public final class MS_JOIN_CONNECTION_TYPE {
  public final static MS_JOIN_CONNECTION_TYPE MS_DB_XBASE = new MS_JOIN_CONNECTION_TYPE("MS_DB_XBASE");
  public final static MS_JOIN_CONNECTION_TYPE MS_DB_CSV = new MS_JOIN_CONNECTION_TYPE("MS_DB_CSV");
  public final static MS_JOIN_CONNECTION_TYPE MS_DB_MYSQL = new MS_JOIN_CONNECTION_TYPE("MS_DB_MYSQL");
  public final static MS_JOIN_CONNECTION_TYPE MS_DB_ORACLE = new MS_JOIN_CONNECTION_TYPE("MS_DB_ORACLE");
  public final static MS_JOIN_CONNECTION_TYPE MS_DB_POSTGRES = new MS_JOIN_CONNECTION_TYPE("MS_DB_POSTGRES");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static MS_JOIN_CONNECTION_TYPE swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + MS_JOIN_CONNECTION_TYPE.class + " with value " + swigValue);
  }

  private MS_JOIN_CONNECTION_TYPE(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private MS_JOIN_CONNECTION_TYPE(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private MS_JOIN_CONNECTION_TYPE(String swigName, MS_JOIN_CONNECTION_TYPE swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static MS_JOIN_CONNECTION_TYPE[] swigValues = { MS_DB_XBASE, MS_DB_CSV, MS_DB_MYSQL, MS_DB_ORACLE, MS_DB_POSTGRES };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

