/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.umn.gis.mapscript;

public final class MS_PARSE_TYPE_ENUM {
  public final static MS_PARSE_TYPE_ENUM MS_PARSE_TYPE_BOOLEAN = new MS_PARSE_TYPE_ENUM("MS_PARSE_TYPE_BOOLEAN");
  public final static MS_PARSE_TYPE_ENUM MS_PARSE_TYPE_STRING = new MS_PARSE_TYPE_ENUM("MS_PARSE_TYPE_STRING");
  public final static MS_PARSE_TYPE_ENUM MS_PARSE_TYPE_SHAPE = new MS_PARSE_TYPE_ENUM("MS_PARSE_TYPE_SHAPE");
  public final static MS_PARSE_TYPE_ENUM MS_PARSE_TYPE_SLD = new MS_PARSE_TYPE_ENUM("MS_PARSE_TYPE_SLD");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static MS_PARSE_TYPE_ENUM swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + MS_PARSE_TYPE_ENUM.class + " with value " + swigValue);
  }

  private MS_PARSE_TYPE_ENUM(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private MS_PARSE_TYPE_ENUM(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private MS_PARSE_TYPE_ENUM(String swigName, MS_PARSE_TYPE_ENUM swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static MS_PARSE_TYPE_ENUM[] swigValues = { MS_PARSE_TYPE_BOOLEAN, MS_PARSE_TYPE_STRING, MS_PARSE_TYPE_SHAPE, MS_PARSE_TYPE_SLD };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

