/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.umn.gis.mapscript;

public final class MS_QUERY_TYPE {
  public final static MS_QUERY_TYPE MS_QUERY_IS_NULL = new MS_QUERY_TYPE("MS_QUERY_IS_NULL");
  public final static MS_QUERY_TYPE MS_QUERY_BY_POINT = new MS_QUERY_TYPE("MS_QUERY_BY_POINT");
  public final static MS_QUERY_TYPE MS_QUERY_BY_RECT = new MS_QUERY_TYPE("MS_QUERY_BY_RECT");
  public final static MS_QUERY_TYPE MS_QUERY_BY_SHAPE = new MS_QUERY_TYPE("MS_QUERY_BY_SHAPE");
  public final static MS_QUERY_TYPE MS_QUERY_BY_ATTRIBUTE = new MS_QUERY_TYPE("MS_QUERY_BY_ATTRIBUTE");
  public final static MS_QUERY_TYPE MS_QUERY_BY_INDEX = new MS_QUERY_TYPE("MS_QUERY_BY_INDEX");
  public final static MS_QUERY_TYPE MS_QUERY_BY_FILTER = new MS_QUERY_TYPE("MS_QUERY_BY_FILTER");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static MS_QUERY_TYPE swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + MS_QUERY_TYPE.class + " with value " + swigValue);
  }

  private MS_QUERY_TYPE(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private MS_QUERY_TYPE(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private MS_QUERY_TYPE(String swigName, MS_QUERY_TYPE swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static MS_QUERY_TYPE[] swigValues = { MS_QUERY_IS_NULL, MS_QUERY_BY_POINT, MS_QUERY_BY_RECT, MS_QUERY_BY_SHAPE, MS_QUERY_BY_ATTRIBUTE, MS_QUERY_BY_INDEX, MS_QUERY_BY_FILTER };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

