/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.umn.gis.mapscript;

public final class MS_RENDER_MODE {
  public final static MS_RENDER_MODE MS_FIRST_MATCHING_CLASS = new MS_RENDER_MODE("MS_FIRST_MATCHING_CLASS");
  public final static MS_RENDER_MODE MS_ALL_MATCHING_CLASSES = new MS_RENDER_MODE("MS_ALL_MATCHING_CLASSES");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static MS_RENDER_MODE swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + MS_RENDER_MODE.class + " with value " + swigValue);
  }

  private MS_RENDER_MODE(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private MS_RENDER_MODE(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private MS_RENDER_MODE(String swigName, MS_RENDER_MODE swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static MS_RENDER_MODE[] swigValues = { MS_FIRST_MATCHING_CLASS, MS_ALL_MATCHING_CLASSES };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

