/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.umn.gis.mapscript;

public class resultObj {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected resultObj(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(resultObj obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mapscriptJNI.delete_resultObj(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int getShapeindex() {
    return mapscriptJNI.resultObj_shapeindex_get(swigCPtr, this);
  }

  public int getTileindex() {
    return mapscriptJNI.resultObj_tileindex_get(swigCPtr, this);
  }

  public int getResultindex() {
    return mapscriptJNI.resultObj_resultindex_get(swigCPtr, this);
  }

  public int getClassindex() {
    return mapscriptJNI.resultObj_classindex_get(swigCPtr, this);
  }

  public resultObj(int shapeindex) {
    this(mapscriptJNI.new_resultObj(shapeindex), true);
  }

}
