/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.umn.gis.mapscript;

public class scaleTokenObj {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected scaleTokenObj(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(scaleTokenObj obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mapscriptJNI.delete_scaleTokenObj(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setName(String value) {
    mapscriptJNI.scaleTokenObj_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return mapscriptJNI.scaleTokenObj_name_get(swigCPtr, this);
  }

  public void setN_entries(int value) {
    mapscriptJNI.scaleTokenObj_n_entries_set(swigCPtr, this, value);
  }

  public int getN_entries() {
    return mapscriptJNI.scaleTokenObj_n_entries_get(swigCPtr, this);
  }

  public void setTokens(scaleTokenEntryObj value) {
    mapscriptJNI.scaleTokenObj_tokens_set(swigCPtr, this, scaleTokenEntryObj.getCPtr(value), value);
  }

  public scaleTokenEntryObj getTokens() {
    long cPtr = mapscriptJNI.scaleTokenObj_tokens_get(swigCPtr, this);
    return (cPtr == 0) ? null : new scaleTokenEntryObj(cPtr, false);
  }

  public scaleTokenObj() {
    this(mapscriptJNI.new_scaleTokenObj(), true);
  }

}
