/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.umn.gis.mapscript;

public class webObj {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected webObj(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(webObj obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mapscriptJNI.delete_webObj(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public hashTableObj getMetadata() {
    long cPtr = mapscriptJNI.webObj_metadata_get(swigCPtr, this);
    return (cPtr == 0) ? null : new hashTableObj(cPtr, false);
  }

  public hashTableObj getValidation() {
    long cPtr = mapscriptJNI.webObj_validation_get(swigCPtr, this);
    return (cPtr == 0) ? null : new hashTableObj(cPtr, false);
  }

  public mapObj getMap() {
    long cPtr = mapscriptJNI.webObj_map_get(swigCPtr, this);
    return (cPtr == 0) ? null : new mapObj(cPtr, false);
  }

  public void setImagepath(String value) {
    mapscriptJNI.webObj_imagepath_set(swigCPtr, this, value);
  }

  public String getImagepath() {
    return mapscriptJNI.webObj_imagepath_get(swigCPtr, this);
  }

  public void setImageurl(String value) {
    mapscriptJNI.webObj_imageurl_set(swigCPtr, this, value);
  }

  public String getImageurl() {
    return mapscriptJNI.webObj_imageurl_get(swigCPtr, this);
  }

  public void setTemppath(String value) {
    mapscriptJNI.webObj_temppath_set(swigCPtr, this, value);
  }

  public String getTemppath() {
    return mapscriptJNI.webObj_temppath_get(swigCPtr, this);
  }

  public void setHeader(String value) {
    mapscriptJNI.webObj_header_set(swigCPtr, this, value);
  }

  public String getHeader() {
    return mapscriptJNI.webObj_header_get(swigCPtr, this);
  }

  public void setFooter(String value) {
    mapscriptJNI.webObj_footer_set(swigCPtr, this, value);
  }

  public String getFooter() {
    return mapscriptJNI.webObj_footer_get(swigCPtr, this);
  }

  public void setEmpty(String value) {
    mapscriptJNI.webObj_empty_set(swigCPtr, this, value);
  }

  public String getEmpty() {
    return mapscriptJNI.webObj_empty_get(swigCPtr, this);
  }

  public void setError(String value) {
    mapscriptJNI.webObj_error_set(swigCPtr, this, value);
  }

  public String getError() {
    return mapscriptJNI.webObj_error_get(swigCPtr, this);
  }

  public void setMinscaledenom(double value) {
    mapscriptJNI.webObj_minscaledenom_set(swigCPtr, this, value);
  }

  public double getMinscaledenom() {
    return mapscriptJNI.webObj_minscaledenom_get(swigCPtr, this);
  }

  public void setMaxscaledenom(double value) {
    mapscriptJNI.webObj_maxscaledenom_set(swigCPtr, this, value);
  }

  public double getMaxscaledenom() {
    return mapscriptJNI.webObj_maxscaledenom_get(swigCPtr, this);
  }

  public void setMintemplate(String value) {
    mapscriptJNI.webObj_mintemplate_set(swigCPtr, this, value);
  }

  public String getMintemplate() {
    return mapscriptJNI.webObj_mintemplate_get(swigCPtr, this);
  }

  public void setMaxtemplate(String value) {
    mapscriptJNI.webObj_maxtemplate_set(swigCPtr, this, value);
  }

  public String getMaxtemplate() {
    return mapscriptJNI.webObj_maxtemplate_get(swigCPtr, this);
  }

  public void setQueryformat(String value) {
    mapscriptJNI.webObj_queryformat_set(swigCPtr, this, value);
  }

  public String getQueryformat() {
    return mapscriptJNI.webObj_queryformat_get(swigCPtr, this);
  }

  public void setLegendformat(String value) {
    mapscriptJNI.webObj_legendformat_set(swigCPtr, this, value);
  }

  public String getLegendformat() {
    return mapscriptJNI.webObj_legendformat_get(swigCPtr, this);
  }

  public void setBrowseformat(String value) {
    mapscriptJNI.webObj_browseformat_set(swigCPtr, this, value);
  }

  public String getBrowseformat() {
    return mapscriptJNI.webObj_browseformat_get(swigCPtr, this);
  }

  public void setTemplate(String value) {
    mapscriptJNI.webObj_template_set(swigCPtr, this, value);
  }

  public String getTemplate() {
    return mapscriptJNI.webObj_template_get(swigCPtr, this);
  }

  public webObj() {
    this(mapscriptJNI.new_webObj(), true);
  }

  public int updateFromString(String snippet) {
    return mapscriptJNI.webObj_updateFromString(swigCPtr, this, snippet);
  }

  public String convertToString() {
    return mapscriptJNI.webObj_convertToString(swigCPtr, this);
  }

}
