package edu.umn.gis;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

public class classObj {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;
  public layerObj layer;

  protected classObj(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(classObj obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mapscriptJNI.delete_classObj(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setStatus(int value) {
    mapscriptJNI.classObj_status_set(swigCPtr, this, value);
  }

  public int getStatus() {
    return mapscriptJNI.classObj_status_get(swigCPtr, this);
  }

  public void setNumstyles(int value) {
    mapscriptJNI.classObj_numstyles_set(swigCPtr, this, value);
  }

  public int getNumstyles() {
    return mapscriptJNI.classObj_numstyles_get(swigCPtr, this);
  }

  public void setNumlabels(int value) {
    mapscriptJNI.classObj_numlabels_set(swigCPtr, this, value);
  }

  public int getNumlabels() {
    return mapscriptJNI.classObj_numlabels_get(swigCPtr, this);
  }

  public void setName(String value) {
    mapscriptJNI.classObj_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return mapscriptJNI.classObj_name_get(swigCPtr, this);
  }

  public void setTitle(String value) {
    mapscriptJNI.classObj_title_set(swigCPtr, this, value);
  }

  public String getTitle() {
    return mapscriptJNI.classObj_title_get(swigCPtr, this);
  }

  public void setTemplate(String value) {
    mapscriptJNI.classObj_template_set(swigCPtr, this, value);
  }

  public String getTemplate() {
    return mapscriptJNI.classObj_template_get(swigCPtr, this);
  }

  public void setType(int value) {
    mapscriptJNI.classObj_type_set(swigCPtr, this, value);
  }

  public int getType() {
    return mapscriptJNI.classObj_type_get(swigCPtr, this);
  }

  public hashTableObj getMetadata() {
    long cPtr = mapscriptJNI.classObj_metadata_get(swigCPtr, this);
    return (cPtr == 0) ? null : new hashTableObj(cPtr, false);
  }

  public hashTableObj getValidation() {
    long cPtr = mapscriptJNI.classObj_validation_get(swigCPtr, this);
    return (cPtr == 0) ? null : new hashTableObj(cPtr, false);
  }

  public void setMinscaledenom(double value) {
    mapscriptJNI.classObj_minscaledenom_set(swigCPtr, this, value);
  }

  public double getMinscaledenom() {
    return mapscriptJNI.classObj_minscaledenom_get(swigCPtr, this);
  }

  public void setMaxscaledenom(double value) {
    mapscriptJNI.classObj_maxscaledenom_set(swigCPtr, this, value);
  }

  public double getMaxscaledenom() {
    return mapscriptJNI.classObj_maxscaledenom_get(swigCPtr, this);
  }

  public void setMinfeaturesize(int value) {
    mapscriptJNI.classObj_minfeaturesize_set(swigCPtr, this, value);
  }

  public int getMinfeaturesize() {
    return mapscriptJNI.classObj_minfeaturesize_get(swigCPtr, this);
  }

  public int getRefcount() {
    return mapscriptJNI.classObj_refcount_get(swigCPtr, this);
  }

  public layerObj getLayer() {
    long cPtr = mapscriptJNI.classObj_layer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new layerObj(cPtr, false);
  }

  public void setDebug(int value) {
    mapscriptJNI.classObj_debug_set(swigCPtr, this, value);
  }

  public int getDebug() {
    return mapscriptJNI.classObj_debug_get(swigCPtr, this);
  }

  public void setKeyimage(String value) {
    mapscriptJNI.classObj_keyimage_set(swigCPtr, this, value);
  }

  public String getKeyimage() {
    return mapscriptJNI.classObj_keyimage_get(swigCPtr, this);
  }

  public void setGroup(String value) {
    mapscriptJNI.classObj_group_set(swigCPtr, this, value);
  }

  public String getGroup() {
    return mapscriptJNI.classObj_group_get(swigCPtr, this);
  }

  public void setLeader(labelLeaderObj value) {
    mapscriptJNI.classObj_leader_set(swigCPtr, this, labelLeaderObj.getCPtr(value), value);
  }

  public labelLeaderObj getLeader() {
    long cPtr = mapscriptJNI.classObj_leader_get(swigCPtr, this);
    return (cPtr == 0) ? null : new labelLeaderObj(cPtr, false);
  }

  public classObj(layerObj layer) {
    this(mapscriptJNI.new_classObj(layerObj.getCPtr(layer), layer), true);
  }

  public int updateFromString(String snippet) {
    return mapscriptJNI.classObj_updateFromString(swigCPtr, this, snippet);
  }

  public classObj cloneClass() {
    long cPtr = mapscriptJNI.classObj_cloneClass(swigCPtr, this);
    return (cPtr == 0) ? null : new classObj(cPtr, true);
  }

  public int setExpression(String expression) {
    return mapscriptJNI.classObj_setExpression(swigCPtr, this, expression);
  }

  public String getExpressionString() {
    return mapscriptJNI.classObj_getExpressionString(swigCPtr, this);
  }

  public int setText(String text) {
    return mapscriptJNI.classObj_setText(swigCPtr, this, text);
  }

  public String getTextString() {
    return mapscriptJNI.classObj_getTextString(swigCPtr, this);
  }

  public String getMetaData(String name) {
    return mapscriptJNI.classObj_getMetaData(swigCPtr, this, name);
  }

  public int setMetaData(String name, String value) {
    return mapscriptJNI.classObj_setMetaData(swigCPtr, this, name, value);
  }

  public String getFirstMetaDataKey() {
    return mapscriptJNI.classObj_getFirstMetaDataKey(swigCPtr, this);
  }

  public String getNextMetaDataKey(String lastkey) {
    return mapscriptJNI.classObj_getNextMetaDataKey(swigCPtr, this, lastkey);
  }

  public int drawLegendIcon(mapObj map, layerObj layer, int width, int height, imageObj dstImage, int dstX, int dstY) {
    return mapscriptJNI.classObj_drawLegendIcon(swigCPtr, this, mapObj.getCPtr(map), map, layerObj.getCPtr(layer),
        layer, width, height, imageObj.getCPtr(dstImage), dstImage, dstX, dstY);
  }

  public imageObj createLegendIcon(mapObj map, layerObj layer, int width, int height) {
    long cPtr = mapscriptJNI.classObj_createLegendIcon(swigCPtr, this, mapObj.getCPtr(map), map,
        layerObj.getCPtr(layer), layer, width, height);
    return (cPtr == 0) ? null : new imageObj(cPtr, true);
  }

  public styleObj getStyle(int i) {
    long cPtr = mapscriptJNI.classObj_getStyle(swigCPtr, this, i);
    return (cPtr == 0) ? null : new styleObj(cPtr, true);
  }

  public int insertStyle(styleObj style, int index) {
    return mapscriptJNI.classObj_insertStyle(swigCPtr, this, styleObj.getCPtr(style), style, index);
  }

  public styleObj removeStyle(int index) {
    long cPtr = mapscriptJNI.classObj_removeStyle(swigCPtr, this, index);
    return (cPtr == 0) ? null : new styleObj(cPtr, true);
  }

  public int moveStyleUp(int index) {
    return mapscriptJNI.classObj_moveStyleUp(swigCPtr, this, index);
  }

  public int moveStyleDown(int index) {
    return mapscriptJNI.classObj_moveStyleDown(swigCPtr, this, index);
  }

}
