package edu.umn.gis;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

public class labelLeaderObj {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected labelLeaderObj(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(labelLeaderObj obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mapscriptJNI.delete_labelLeaderObj(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMaxdistance(int value) {
    mapscriptJNI.labelLeaderObj_maxdistance_set(swigCPtr, this, value);
  }

  public int getMaxdistance() {
    return mapscriptJNI.labelLeaderObj_maxdistance_get(swigCPtr, this);
  }

  public void setGridstep(int value) {
    mapscriptJNI.labelLeaderObj_gridstep_set(swigCPtr, this, value);
  }

  public int getGridstep() {
    return mapscriptJNI.labelLeaderObj_gridstep_get(swigCPtr, this);
  }

  public void setNumstyles(int value) {
    mapscriptJNI.labelLeaderObj_numstyles_set(swigCPtr, this, value);
  }

  public int getNumstyles() {
    return mapscriptJNI.labelLeaderObj_numstyles_get(swigCPtr, this);
  }

  public labelLeaderObj() {
    this(mapscriptJNI.new_labelLeaderObj(), true);
  }

}
