package edu.umn.gis;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

public class labelCacheSlotObj {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected labelCacheSlotObj(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(labelCacheSlotObj obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mapscriptJNI.delete_labelCacheSlotObj(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public labelCacheMemberObj getLabels() {
    long cPtr = mapscriptJNI.labelCacheSlotObj_labels_get(swigCPtr, this);
    return (cPtr == 0) ? null : new labelCacheMemberObj(cPtr, false);
  }

  public int getNumlabels() {
    return mapscriptJNI.labelCacheSlotObj_numlabels_get(swigCPtr, this);
  }

  public int getCachesize() {
    return mapscriptJNI.labelCacheSlotObj_cachesize_get(swigCPtr, this);
  }

  public markerCacheMemberObj getMarkers() {
    long cPtr = mapscriptJNI.labelCacheSlotObj_markers_get(swigCPtr, this);
    return (cPtr == 0) ? null : new markerCacheMemberObj(cPtr, false);
  }

  public int getNummarkers() {
    return mapscriptJNI.labelCacheSlotObj_nummarkers_get(swigCPtr, this);
  }

  public int getMarkercachesize() {
    return mapscriptJNI.labelCacheSlotObj_markercachesize_get(swigCPtr, this);
  }

  public labelCacheSlotObj() {
    this(mapscriptJNI.new_labelCacheSlotObj(), true);
  }

}
