package edu.umn.gis;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

public class labelStyleObj {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected labelStyleObj(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(labelStyleObj obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mapscriptJNI.delete_labelStyleObj(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFonts(SWIGTYPE_p_p_char value) {
    mapscriptJNI.labelStyleObj_fonts_set(swigCPtr, this, SWIGTYPE_p_p_char.getCPtr(value));
  }

  public SWIGTYPE_p_p_char getFonts() {
    long cPtr = mapscriptJNI.labelStyleObj_fonts_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_char(cPtr, false);
  }

  public void setNumfonts(int value) {
    mapscriptJNI.labelStyleObj_numfonts_set(swigCPtr, this, value);
  }

  public int getNumfonts() {
    return mapscriptJNI.labelStyleObj_numfonts_get(swigCPtr, this);
  }

  public void setSize(double value) {
    mapscriptJNI.labelStyleObj_size_set(swigCPtr, this, value);
  }

  public double getSize() {
    return mapscriptJNI.labelStyleObj_size_get(swigCPtr, this);
  }

  public void setRotation(double value) {
    mapscriptJNI.labelStyleObj_rotation_set(swigCPtr, this, value);
  }

  public double getRotation() {
    return mapscriptJNI.labelStyleObj_rotation_get(swigCPtr, this);
  }

  public void setColor(colorObj value) {
    mapscriptJNI.labelStyleObj_color_set(swigCPtr, this, colorObj.getCPtr(value), value);
  }

  public colorObj getColor() {
    long cPtr = mapscriptJNI.labelStyleObj_color_get(swigCPtr, this);
    return (cPtr == 0) ? null : new colorObj(cPtr, false);
  }

  public void setOutlinewidth(double value) {
    mapscriptJNI.labelStyleObj_outlinewidth_set(swigCPtr, this, value);
  }

  public double getOutlinewidth() {
    return mapscriptJNI.labelStyleObj_outlinewidth_get(swigCPtr, this);
  }

  public void setOutlinecolor(colorObj value) {
    mapscriptJNI.labelStyleObj_outlinecolor_set(swigCPtr, this, colorObj.getCPtr(value), value);
  }

  public colorObj getOutlinecolor() {
    long cPtr = mapscriptJNI.labelStyleObj_outlinecolor_get(swigCPtr, this);
    return (cPtr == 0) ? null : new colorObj(cPtr, false);
  }

  public void setAntialias(int value) {
    mapscriptJNI.labelStyleObj_antialias_set(swigCPtr, this, value);
  }

  public int getAntialias() {
    return mapscriptJNI.labelStyleObj_antialias_get(swigCPtr, this);
  }

  public labelStyleObj() {
    this(mapscriptJNI.new_labelStyleObj(), true);
  }

}
