package edu.umn.gis;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

public class labelCacheObj {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected labelCacheObj(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(labelCacheObj obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mapscriptJNI.delete_labelCacheObj(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public labelCacheSlotObj getSlots() {
    long cPtr = mapscriptJNI.labelCacheObj_slots_get(swigCPtr, this);
    return (cPtr == 0) ? null : new labelCacheSlotObj(cPtr, false);
  }

  public int getNumlabels() {
    return mapscriptJNI.labelCacheObj_numlabels_get(swigCPtr, this);
  }

  public int getGutter() {
    return mapscriptJNI.labelCacheObj_gutter_get(swigCPtr, this);
  }

  public void freeCache() {
    mapscriptJNI.labelCacheObj_freeCache(swigCPtr, this);
  }

  public labelCacheObj() {
    this(mapscriptJNI.new_labelCacheObj(), true);
  }

}
