package edu.umn.gis;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

public class layerObj {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;
  public mapObj map;

  protected layerObj(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(layerObj obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mapscriptJNI.delete_layerObj(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setClassitem(String value) {
    mapscriptJNI.layerObj_classitem_set(swigCPtr, this, value);
  }

  public String getClassitem() {
    return mapscriptJNI.layerObj_classitem_get(swigCPtr, this);
  }

  public int getRefcount() {
    return mapscriptJNI.layerObj_refcount_get(swigCPtr, this);
  }

  public int getNumclasses() {
    return mapscriptJNI.layerObj_numclasses_get(swigCPtr, this);
  }

  public int getMaxclasses() {
    return mapscriptJNI.layerObj_maxclasses_get(swigCPtr, this);
  }

  public int getIndex() {
    return mapscriptJNI.layerObj_index_get(swigCPtr, this);
  }

  public mapObj getMap() {
    long cPtr = mapscriptJNI.layerObj_map_get(swigCPtr, this);
    return (cPtr == 0) ? null : new mapObj(cPtr, false);
  }

  public void setHeader(String value) {
    mapscriptJNI.layerObj_header_set(swigCPtr, this, value);
  }

  public String getHeader() {
    return mapscriptJNI.layerObj_header_get(swigCPtr, this);
  }

  public void setFooter(String value) {
    mapscriptJNI.layerObj_footer_set(swigCPtr, this, value);
  }

  public String getFooter() {
    return mapscriptJNI.layerObj_footer_get(swigCPtr, this);
  }

  public void setTemplate(String value) {
    mapscriptJNI.layerObj_template_set(swigCPtr, this, value);
  }

  public String getTemplate() {
    return mapscriptJNI.layerObj_template_get(swigCPtr, this);
  }

  public void setName(String value) {
    mapscriptJNI.layerObj_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return mapscriptJNI.layerObj_name_get(swigCPtr, this);
  }

  public void setGroup(String value) {
    mapscriptJNI.layerObj_group_set(swigCPtr, this, value);
  }

  public String getGroup() {
    return mapscriptJNI.layerObj_group_get(swigCPtr, this);
  }

  public void setStatus(int value) {
    mapscriptJNI.layerObj_status_set(swigCPtr, this, value);
  }

  public int getStatus() {
    return mapscriptJNI.layerObj_status_get(swigCPtr, this);
  }

  public void setData(String value) {
    mapscriptJNI.layerObj_data_set(swigCPtr, this, value);
  }

  public String getData() {
    return mapscriptJNI.layerObj_data_get(swigCPtr, this);
  }

  public void setType(MS_LAYER_TYPE value) {
    mapscriptJNI.layerObj_type_set(swigCPtr, this, value.swigValue());
  }

  public MS_LAYER_TYPE getType() {
    return MS_LAYER_TYPE.swigToEnum(mapscriptJNI.layerObj_type_get(swigCPtr, this));
  }

  public void setTolerance(double value) {
    mapscriptJNI.layerObj_tolerance_set(swigCPtr, this, value);
  }

  public double getTolerance() {
    return mapscriptJNI.layerObj_tolerance_get(swigCPtr, this);
  }

  public void setToleranceunits(int value) {
    mapscriptJNI.layerObj_toleranceunits_set(swigCPtr, this, value);
  }

  public int getToleranceunits() {
    return mapscriptJNI.layerObj_toleranceunits_get(swigCPtr, this);
  }

  public void setSymbolscaledenom(double value) {
    mapscriptJNI.layerObj_symbolscaledenom_set(swigCPtr, this, value);
  }

  public double getSymbolscaledenom() {
    return mapscriptJNI.layerObj_symbolscaledenom_get(swigCPtr, this);
  }

  public void setMinscaledenom(double value) {
    mapscriptJNI.layerObj_minscaledenom_set(swigCPtr, this, value);
  }

  public double getMinscaledenom() {
    return mapscriptJNI.layerObj_minscaledenom_get(swigCPtr, this);
  }

  public void setMaxscaledenom(double value) {
    mapscriptJNI.layerObj_maxscaledenom_set(swigCPtr, this, value);
  }

  public double getMaxscaledenom() {
    return mapscriptJNI.layerObj_maxscaledenom_get(swigCPtr, this);
  }

  public void setMinfeaturesize(int value) {
    mapscriptJNI.layerObj_minfeaturesize_set(swigCPtr, this, value);
  }

  public int getMinfeaturesize() {
    return mapscriptJNI.layerObj_minfeaturesize_get(swigCPtr, this);
  }

  public void setLabelminscaledenom(double value) {
    mapscriptJNI.layerObj_labelminscaledenom_set(swigCPtr, this, value);
  }

  public double getLabelminscaledenom() {
    return mapscriptJNI.layerObj_labelminscaledenom_get(swigCPtr, this);
  }

  public void setLabelmaxscaledenom(double value) {
    mapscriptJNI.layerObj_labelmaxscaledenom_set(swigCPtr, this, value);
  }

  public double getLabelmaxscaledenom() {
    return mapscriptJNI.layerObj_labelmaxscaledenom_get(swigCPtr, this);
  }

  public void setMingeowidth(double value) {
    mapscriptJNI.layerObj_mingeowidth_set(swigCPtr, this, value);
  }

  public double getMingeowidth() {
    return mapscriptJNI.layerObj_mingeowidth_get(swigCPtr, this);
  }

  public void setMaxgeowidth(double value) {
    mapscriptJNI.layerObj_maxgeowidth_set(swigCPtr, this, value);
  }

  public double getMaxgeowidth() {
    return mapscriptJNI.layerObj_maxgeowidth_get(swigCPtr, this);
  }

  public void setSizeunits(int value) {
    mapscriptJNI.layerObj_sizeunits_set(swigCPtr, this, value);
  }

  public int getSizeunits() {
    return mapscriptJNI.layerObj_sizeunits_get(swigCPtr, this);
  }

  public void setMaxfeatures(int value) {
    mapscriptJNI.layerObj_maxfeatures_set(swigCPtr, this, value);
  }

  public int getMaxfeatures() {
    return mapscriptJNI.layerObj_maxfeatures_get(swigCPtr, this);
  }

  public void setStartindex(int value) {
    mapscriptJNI.layerObj_startindex_set(swigCPtr, this, value);
  }

  public int getStartindex() {
    return mapscriptJNI.layerObj_startindex_get(swigCPtr, this);
  }

  public void setOffsite(colorObj value) {
    mapscriptJNI.layerObj_offsite_set(swigCPtr, this, colorObj.getCPtr(value), value);
  }

  public colorObj getOffsite() {
    long cPtr = mapscriptJNI.layerObj_offsite_get(swigCPtr, this);
    return (cPtr == 0) ? null : new colorObj(cPtr, false);
  }

  public void setTransform(int value) {
    mapscriptJNI.layerObj_transform_set(swigCPtr, this, value);
  }

  public int getTransform() {
    return mapscriptJNI.layerObj_transform_get(swigCPtr, this);
  }

  public void setLabelcache(int value) {
    mapscriptJNI.layerObj_labelcache_set(swigCPtr, this, value);
  }

  public int getLabelcache() {
    return mapscriptJNI.layerObj_labelcache_get(swigCPtr, this);
  }

  public void setPostlabelcache(int value) {
    mapscriptJNI.layerObj_postlabelcache_set(swigCPtr, this, value);
  }

  public int getPostlabelcache() {
    return mapscriptJNI.layerObj_postlabelcache_get(swigCPtr, this);
  }

  public void setLabelitem(String value) {
    mapscriptJNI.layerObj_labelitem_set(swigCPtr, this, value);
  }

  public String getLabelitem() {
    return mapscriptJNI.layerObj_labelitem_get(swigCPtr, this);
  }

  public void setTileitem(String value) {
    mapscriptJNI.layerObj_tileitem_set(swigCPtr, this, value);
  }

  public String getTileitem() {
    return mapscriptJNI.layerObj_tileitem_get(swigCPtr, this);
  }

  public void setTileindex(String value) {
    mapscriptJNI.layerObj_tileindex_set(swigCPtr, this, value);
  }

  public String getTileindex() {
    return mapscriptJNI.layerObj_tileindex_get(swigCPtr, this);
  }

  public void setUnits(int value) {
    mapscriptJNI.layerObj_units_set(swigCPtr, this, value);
  }

  public int getUnits() {
    return mapscriptJNI.layerObj_units_get(swigCPtr, this);
  }

  public void setConnection(String value) {
    mapscriptJNI.layerObj_connection_set(swigCPtr, this, value);
  }

  public String getConnection() {
    return mapscriptJNI.layerObj_connection_get(swigCPtr, this);
  }

  public void setPlugin_library(String value) {
    mapscriptJNI.layerObj_plugin_library_set(swigCPtr, this, value);
  }

  public String getPlugin_library() {
    return mapscriptJNI.layerObj_plugin_library_get(swigCPtr, this);
  }

  public void setPlugin_library_original(String value) {
    mapscriptJNI.layerObj_plugin_library_original_set(swigCPtr, this, value);
  }

  public String getPlugin_library_original() {
    return mapscriptJNI.layerObj_plugin_library_original_get(swigCPtr, this);
  }

  public void setConnectiontype(MS_CONNECTION_TYPE value) {
    mapscriptJNI.layerObj_connectiontype_set(swigCPtr, this, value.swigValue());
  }

  public MS_CONNECTION_TYPE getConnectiontype() {
    return MS_CONNECTION_TYPE.swigToEnum(mapscriptJNI.layerObj_connectiontype_get(swigCPtr, this));
  }

  public int getNumitems() {
    return mapscriptJNI.layerObj_numitems_get(swigCPtr, this);
  }

  public void setBandsitem(String value) {
    mapscriptJNI.layerObj_bandsitem_set(swigCPtr, this, value);
  }

  public String getBandsitem() {
    return mapscriptJNI.layerObj_bandsitem_get(swigCPtr, this);
  }

  public void setFilteritem(String value) {
    mapscriptJNI.layerObj_filteritem_set(swigCPtr, this, value);
  }

  public String getFilteritem() {
    return mapscriptJNI.layerObj_filteritem_get(swigCPtr, this);
  }

  public void setStyleitem(String value) {
    mapscriptJNI.layerObj_styleitem_set(swigCPtr, this, value);
  }

  public String getStyleitem() {
    return mapscriptJNI.layerObj_styleitem_get(swigCPtr, this);
  }

  public void setRequires(String value) {
    mapscriptJNI.layerObj_requires_set(swigCPtr, this, value);
  }

  public String getRequires() {
    return mapscriptJNI.layerObj_requires_get(swigCPtr, this);
  }

  public void setLabelrequires(String value) {
    mapscriptJNI.layerObj_labelrequires_set(swigCPtr, this, value);
  }

  public String getLabelrequires() {
    return mapscriptJNI.layerObj_labelrequires_get(swigCPtr, this);
  }

  public hashTableObj getMetadata() {
    long cPtr = mapscriptJNI.layerObj_metadata_get(swigCPtr, this);
    return (cPtr == 0) ? null : new hashTableObj(cPtr, false);
  }

  public hashTableObj getValidation() {
    long cPtr = mapscriptJNI.layerObj_validation_get(swigCPtr, this);
    return (cPtr == 0) ? null : new hashTableObj(cPtr, false);
  }

  public hashTableObj getBindvals() {
    long cPtr = mapscriptJNI.layerObj_bindvals_get(swigCPtr, this);
    return (cPtr == 0) ? null : new hashTableObj(cPtr, false);
  }

  public clusterObj getCluster() {
    long cPtr = mapscriptJNI.layerObj_cluster_get(swigCPtr, this);
    return (cPtr == 0) ? null : new clusterObj(cPtr, false);
  }

  public void setOpacity(int value) {
    mapscriptJNI.layerObj_opacity_set(swigCPtr, this, value);
  }

  public int getOpacity() {
    return mapscriptJNI.layerObj_opacity_get(swigCPtr, this);
  }

  public void setDump(int value) {
    mapscriptJNI.layerObj_dump_set(swigCPtr, this, value);
  }

  public int getDump() {
    return mapscriptJNI.layerObj_dump_get(swigCPtr, this);
  }

  public void setDebug(int value) {
    mapscriptJNI.layerObj_debug_set(swigCPtr, this, value);
  }

  public int getDebug() {
    return mapscriptJNI.layerObj_debug_get(swigCPtr, this);
  }

  public int getNumprocessing() {
    return mapscriptJNI.layerObj_numprocessing_get(swigCPtr, this);
  }

  public int getNumjoins() {
    return mapscriptJNI.layerObj_numjoins_get(swigCPtr, this);
  }

  public void setClassgroup(String value) {
    mapscriptJNI.layerObj_classgroup_set(swigCPtr, this, value);
  }

  public String getClassgroup() {
    return mapscriptJNI.layerObj_classgroup_get(swigCPtr, this);
  }

  public void setMasklayer(String value) {
    mapscriptJNI.layerObj_masklayer_set(swigCPtr, this, value);
  }

  public String getMasklayer() {
    return mapscriptJNI.layerObj_masklayer_get(swigCPtr, this);
  }

  public layerObj(mapObj map) {
    this(mapscriptJNI.new_layerObj(mapObj.getCPtr(map), map), true);
  }

  public layerObj cloneLayer() {
    long cPtr = mapscriptJNI.layerObj_cloneLayer(swigCPtr, this);
    return (cPtr == 0) ? null : new layerObj(cPtr, true);
  }

  public int updateFromString(String snippet) {
    return mapscriptJNI.layerObj_updateFromString(swigCPtr, this, snippet);
  }

  public int insertClass(classObj classobj, int index) {
    // call the C API
    int actualIndex = mapscriptJNI.layerObj_insertClass(swigCPtr, this, classObj.getCPtr(classobj), classobj, index);
    /* Store parent reference, item 3.2 */
    classobj.layer = this;
    return actualIndex;
  }

  public classObj removeClass(int index) {
    long cPtr = mapscriptJNI.layerObj_removeClass(swigCPtr, this, index);
    return (cPtr == 0) ? null : new classObj(cPtr, true);
  }

  public int open() {
    return mapscriptJNI.layerObj_open(swigCPtr, this);
  }

  public int whichShapes(rectObj rect) {
    return mapscriptJNI.layerObj_whichShapes(swigCPtr, this, rectObj.getCPtr(rect), rect);
  }

  public shapeObj nextShape() {
    long cPtr = mapscriptJNI.layerObj_nextShape(swigCPtr, this);
    return (cPtr == 0) ? null : new shapeObj(cPtr, true);
  }

  public void close() {
    mapscriptJNI.layerObj_close(swigCPtr, this);
  }

  public shapeObj getShape(resultObj record) {
    long cPtr = mapscriptJNI.layerObj_getShape(swigCPtr, this, resultObj.getCPtr(record), record);
    return (cPtr == 0) ? null : new shapeObj(cPtr, true);
  }

  public int getNumResults() {
    return mapscriptJNI.layerObj_getNumResults(swigCPtr, this);
  }

  public rectObj getResultsBounds() {
    long cPtr = mapscriptJNI.layerObj_getResultsBounds(swigCPtr, this);
    return (cPtr == 0) ? null : new rectObj(cPtr, true);
  }

  public resultObj getResult(int i) {
    long cPtr = mapscriptJNI.layerObj_getResult(swigCPtr, this, i);
    return (cPtr == 0) ? null : new resultObj(cPtr, false);
  }

  public classObj getClass(int i) {
    // call the C API
    long cPtr = mapscriptJNI.layerObj_getClass(swigCPtr, this, i);
    classObj clazz = null;
    if (cPtr != 0) {
      clazz = new classObj(cPtr, true);
      /* Store parent reference, item 3.2 */
      clazz.layer = this;
    }
    return clazz;
  }

  public String getItem(int i) {
    return mapscriptJNI.layerObj_getItem(swigCPtr, this, i);
  }

  public int setItems(SWIGTYPE_p_p_char items, int numitems) {
    return mapscriptJNI.layerObj_setItems(swigCPtr, this, SWIGTYPE_p_p_char.getCPtr(items), numitems);
  }

  public int draw(mapObj map, imageObj image) {
    return mapscriptJNI.layerObj_draw(swigCPtr, this, mapObj.getCPtr(map), map, imageObj.getCPtr(image), image);
  }

  public int drawQuery(mapObj map, imageObj image) {
    return mapscriptJNI.layerObj_drawQuery(swigCPtr, this, mapObj.getCPtr(map), map, imageObj.getCPtr(image), image);
  }

  public int queryByFilter(mapObj map, String string) {
    return mapscriptJNI.layerObj_queryByFilter(swigCPtr, this, mapObj.getCPtr(map), map, string);
  }

  public int queryByAttributes(mapObj map, String qitem, String qstring, int mode) {
    return mapscriptJNI.layerObj_queryByAttributes(swigCPtr, this, mapObj.getCPtr(map), map, qitem, qstring, mode);
  }

  public int queryByPoint(mapObj map, pointObj point, int mode, double buffer) {
    return mapscriptJNI.layerObj_queryByPoint(swigCPtr, this, mapObj.getCPtr(map), map, pointObj.getCPtr(point), point,
        mode, buffer);
  }

  public int queryByRect(mapObj map, rectObj rect) {
    return mapscriptJNI.layerObj_queryByRect(swigCPtr, this, mapObj.getCPtr(map), map, rectObj.getCPtr(rect), rect);
  }

  public int queryByFeatures(mapObj map, int slayer) {
    return mapscriptJNI.layerObj_queryByFeatures(swigCPtr, this, mapObj.getCPtr(map), map, slayer);
  }

  public int queryByShape(mapObj map, shapeObj shape) {
    return mapscriptJNI.layerObj_queryByShape(swigCPtr, this, mapObj.getCPtr(map), map, shapeObj.getCPtr(shape), shape);
  }

  public int queryByIndex(mapObj map, int tileindex, int shapeindex, int bAddToQuery) {
    return mapscriptJNI.layerObj_queryByIndex(swigCPtr, this, mapObj.getCPtr(map), map, tileindex, shapeindex,
        bAddToQuery);
  }

  public resultCacheObj getResults() {
    long cPtr = mapscriptJNI.layerObj_getResults(swigCPtr, this);
    return (cPtr == 0) ? null : new resultCacheObj(cPtr, false);
  }

  public int setFilter(String filter) {
    return mapscriptJNI.layerObj_setFilter(swigCPtr, this, filter);
  }

  public String getFilterString() {
    return mapscriptJNI.layerObj_getFilterString(swigCPtr, this);
  }

  public int setWKTProjection(String wkt) {
    return mapscriptJNI.layerObj_setWKTProjection(swigCPtr, this, wkt);
  }

  public String getProjection() {
    return mapscriptJNI.layerObj_getProjection(swigCPtr, this);
  }

  public int setProjection(String proj4) {
    return mapscriptJNI.layerObj_setProjection(swigCPtr, this, proj4);
  }

  public int addFeature(shapeObj shape) {
    return mapscriptJNI.layerObj_addFeature(swigCPtr, this, shapeObj.getCPtr(shape), shape);
  }

  public int getNumFeatures() {
    return mapscriptJNI.layerObj_getNumFeatures(swigCPtr, this);
  }

  public rectObj getExtent() {
    long cPtr = mapscriptJNI.layerObj_getExtent(swigCPtr, this);
    return (cPtr == 0) ? null : new rectObj(cPtr, true);
  }

  public int setExtent(double minx, double miny, double maxx, double maxy) {
    return mapscriptJNI.layerObj_setExtent(swigCPtr, this, minx, miny, maxx, maxy);
  }

  public String getMetaData(String name) {
    return mapscriptJNI.layerObj_getMetaData(swigCPtr, this, name);
  }

  public int setMetaData(String name, String value) {
    return mapscriptJNI.layerObj_setMetaData(swigCPtr, this, name, value);
  }

  public int removeMetaData(String name) {
    return mapscriptJNI.layerObj_removeMetaData(swigCPtr, this, name);
  }

  public String getFirstMetaDataKey() {
    return mapscriptJNI.layerObj_getFirstMetaDataKey(swigCPtr, this);
  }

  public String getNextMetaDataKey(String lastkey) {
    return mapscriptJNI.layerObj_getNextMetaDataKey(swigCPtr, this, lastkey);
  }

  public String getWMSFeatureInfoURL(mapObj map, int click_x, int click_y, int feature_count, String info_format) {
    return mapscriptJNI.layerObj_getWMSFeatureInfoURL(swigCPtr, this, mapObj.getCPtr(map), map, click_x, click_y,
        feature_count, info_format);
  }

  public String executeWFSGetFeature(layerObj layer) {
    return mapscriptJNI.layerObj_executeWFSGetFeature(swigCPtr, this, layerObj.getCPtr(layer), layer);
  }

  public int applySLD(String sld, String stylelayer) {
    return mapscriptJNI.layerObj_applySLD(swigCPtr, this, sld, stylelayer);
  }

  public int applySLDURL(String sld, String stylelayer) {
    return mapscriptJNI.layerObj_applySLDURL(swigCPtr, this, sld, stylelayer);
  }

  public String generateSLD() {
    return mapscriptJNI.layerObj_generateSLD(swigCPtr, this);
  }

  public int isVisible() {
    return mapscriptJNI.layerObj_isVisible(swigCPtr, this);
  }

  public int moveClassUp(int index) {
    return mapscriptJNI.layerObj_moveClassUp(swigCPtr, this, index);
  }

  public int moveClassDown(int index) {
    return mapscriptJNI.layerObj_moveClassDown(swigCPtr, this, index);
  }

  public void setProcessingKey(String key, String value) {
    mapscriptJNI.layerObj_setProcessingKey(swigCPtr, this, key, value);
  }

  public void setProcessing(String directive) {
    mapscriptJNI.layerObj_setProcessing(swigCPtr, this, directive);
  }

  public void addProcessing(String directive) {
    mapscriptJNI.layerObj_addProcessing(swigCPtr, this, directive);
  }

  public String getProcessing(int index) {
    return mapscriptJNI.layerObj_getProcessing(swigCPtr, this, index);
  }

  public String getProcessingKey(String key) {
    return mapscriptJNI.layerObj_getProcessingKey(swigCPtr, this, key);
  }

  public int clearProcessing() {
    return mapscriptJNI.layerObj_clearProcessing(swigCPtr, this);
  }

  public int setConnectionType(int connectiontype, String library_str) {
    return mapscriptJNI.layerObj_setConnectionType(swigCPtr, this, connectiontype, library_str);
  }

  public int getClassIndex(mapObj map, shapeObj shape, SWIGTYPE_p_int classgroup, int numclasses) {
    return mapscriptJNI.layerObj_getClassIndex(swigCPtr, this, mapObj.getCPtr(map), map, shapeObj.getCPtr(shape), shape,
        SWIGTYPE_p_int.getCPtr(classgroup), numclasses);
  }

}
