package edu.umn.gis;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

public class legendObj {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected legendObj(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(legendObj obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mapscriptJNI.delete_legendObj(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setImagecolor(colorObj value) {
    mapscriptJNI.legendObj_imagecolor_set(swigCPtr, this, colorObj.getCPtr(value), value);
  }

  public colorObj getImagecolor() {
    long cPtr = mapscriptJNI.legendObj_imagecolor_get(swigCPtr, this);
    return (cPtr == 0) ? null : new colorObj(cPtr, false);
  }

  public labelObj getLabel() {
    long cPtr = mapscriptJNI.legendObj_label_get(swigCPtr, this);
    return (cPtr == 0) ? null : new labelObj(cPtr, false);
  }

  public void setKeysizex(int value) {
    mapscriptJNI.legendObj_keysizex_set(swigCPtr, this, value);
  }

  public int getKeysizex() {
    return mapscriptJNI.legendObj_keysizex_get(swigCPtr, this);
  }

  public void setKeysizey(int value) {
    mapscriptJNI.legendObj_keysizey_set(swigCPtr, this, value);
  }

  public int getKeysizey() {
    return mapscriptJNI.legendObj_keysizey_get(swigCPtr, this);
  }

  public void setKeyspacingx(int value) {
    mapscriptJNI.legendObj_keyspacingx_set(swigCPtr, this, value);
  }

  public int getKeyspacingx() {
    return mapscriptJNI.legendObj_keyspacingx_get(swigCPtr, this);
  }

  public void setKeyspacingy(int value) {
    mapscriptJNI.legendObj_keyspacingy_set(swigCPtr, this, value);
  }

  public int getKeyspacingy() {
    return mapscriptJNI.legendObj_keyspacingy_get(swigCPtr, this);
  }

  public void setOutlinecolor(colorObj value) {
    mapscriptJNI.legendObj_outlinecolor_set(swigCPtr, this, colorObj.getCPtr(value), value);
  }

  public colorObj getOutlinecolor() {
    long cPtr = mapscriptJNI.legendObj_outlinecolor_get(swigCPtr, this);
    return (cPtr == 0) ? null : new colorObj(cPtr, false);
  }

  public void setStatus(int value) {
    mapscriptJNI.legendObj_status_set(swigCPtr, this, value);
  }

  public int getStatus() {
    return mapscriptJNI.legendObj_status_get(swigCPtr, this);
  }

  public void setHeight(int value) {
    mapscriptJNI.legendObj_height_set(swigCPtr, this, value);
  }

  public int getHeight() {
    return mapscriptJNI.legendObj_height_get(swigCPtr, this);
  }

  public void setWidth(int value) {
    mapscriptJNI.legendObj_width_set(swigCPtr, this, value);
  }

  public int getWidth() {
    return mapscriptJNI.legendObj_width_get(swigCPtr, this);
  }

  public void setPosition(int value) {
    mapscriptJNI.legendObj_position_set(swigCPtr, this, value);
  }

  public int getPosition() {
    return mapscriptJNI.legendObj_position_get(swigCPtr, this);
  }

  public void setPostlabelcache(int value) {
    mapscriptJNI.legendObj_postlabelcache_set(swigCPtr, this, value);
  }

  public int getPostlabelcache() {
    return mapscriptJNI.legendObj_postlabelcache_get(swigCPtr, this);
  }

  public void setTemplate(String value) {
    mapscriptJNI.legendObj_template_set(swigCPtr, this, value);
  }

  public String getTemplate() {
    return mapscriptJNI.legendObj_template_get(swigCPtr, this);
  }

  public mapObj getMap() {
    long cPtr = mapscriptJNI.legendObj_map_get(swigCPtr, this);
    return (cPtr == 0) ? null : new mapObj(cPtr, false);
  }

  public int updateFromString(String snippet) {
    return mapscriptJNI.legendObj_updateFromString(swigCPtr, this, snippet);
  }

  public legendObj() {
    this(mapscriptJNI.new_legendObj(), true);
  }

}
