package edu.umn.gis;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

public class mapscript implements mapscriptConstants {
  public static int msSaveImage(mapObj map, imageObj img, String filename) {
    return mapscriptJNI.msSaveImage(mapObj.getCPtr(map), map, imageObj.getCPtr(img), img, filename);
  }

  public static void msFreeImage(imageObj img) {
    mapscriptJNI.msFreeImage(imageObj.getCPtr(img), img);
  }

  public static int msSetup() {
    return mapscriptJNI.msSetup();
  }

  public static void msCleanup() {
    mapscriptJNI.msCleanup();
  }

  public static mapObj msLoadMapFromString(String buffer, String new_mappath) {
    long cPtr = mapscriptJNI.msLoadMapFromString(buffer, new_mappath);
    return (cPtr == 0) ? null : new mapObj(cPtr, false);
  }

  public static errorObj msGetErrorObj() {
    long cPtr = mapscriptJNI.msGetErrorObj();
    return (cPtr == 0) ? null : new errorObj(cPtr, false);
  }

  public static void msResetErrorList() {
    mapscriptJNI.msResetErrorList();
  }

  public static String msGetVersion() {
    return mapscriptJNI.msGetVersion();
  }

  public static int msGetVersionInt() {
    return mapscriptJNI.msGetVersionInt();
  }

  public static String msGetErrorString(String delimiter) {
    return mapscriptJNI.msGetErrorString(delimiter);
  }

  public static void msConnPoolCloseUnreferenced() {
    mapscriptJNI.msConnPoolCloseUnreferenced();
  }

  public static void msIO_resetHandlers() {
    mapscriptJNI.msIO_resetHandlers();
  }

  public static void msIO_installStdoutToBuffer() {
    mapscriptJNI.msIO_installStdoutToBuffer();
  }

  public static void msIO_installStdinFromBuffer() {
    mapscriptJNI.msIO_installStdinFromBuffer();
  }

  public static String msIO_stripStdoutBufferContentType() {
    return mapscriptJNI.msIO_stripStdoutBufferContentType();
  }

  public static void msIO_stripStdoutBufferContentHeaders() {
    mapscriptJNI.msIO_stripStdoutBufferContentHeaders();
  }

  public static String msIO_getStdoutBufferString() {
    return mapscriptJNI.msIO_getStdoutBufferString();
  }

  public static byte[] msIO_getStdoutBufferBytes() {
    return mapscriptJNI.msIO_getStdoutBufferBytes();
  }

}
