package edu.umn.gis;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

public final class MS_BITMAP_FONT_SIZES {
  public final static MS_BITMAP_FONT_SIZES MS_TINY = new MS_BITMAP_FONT_SIZES("MS_TINY");
  public final static MS_BITMAP_FONT_SIZES MS_SMALL = new MS_BITMAP_FONT_SIZES("MS_SMALL");
  public final static MS_BITMAP_FONT_SIZES MS_MEDIUM = new MS_BITMAP_FONT_SIZES("MS_MEDIUM");
  public final static MS_BITMAP_FONT_SIZES MS_LARGE = new MS_BITMAP_FONT_SIZES("MS_LARGE");
  public final static MS_BITMAP_FONT_SIZES MS_GIANT = new MS_BITMAP_FONT_SIZES("MS_GIANT");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static MS_BITMAP_FONT_SIZES swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + MS_BITMAP_FONT_SIZES.class + " with value " + swigValue);
  }

  private MS_BITMAP_FONT_SIZES(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private MS_BITMAP_FONT_SIZES(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue + 1;
  }

  private MS_BITMAP_FONT_SIZES(String swigName, MS_BITMAP_FONT_SIZES swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue + 1;
  }

  private static MS_BITMAP_FONT_SIZES[] swigValues = { MS_TINY, MS_SMALL, MS_MEDIUM, MS_LARGE, MS_GIANT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}
