package edu.umn.gis;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

public final class MS_CAPS_JOINS_AND_CORNERS {
  public final static MS_CAPS_JOINS_AND_CORNERS MS_CJC_NONE = new MS_CAPS_JOINS_AND_CORNERS("MS_CJC_NONE");
  public final static MS_CAPS_JOINS_AND_CORNERS MS_CJC_BEVEL = new MS_CAPS_JOINS_AND_CORNERS("MS_CJC_BEVEL");
  public final static MS_CAPS_JOINS_AND_CORNERS MS_CJC_BUTT = new MS_CAPS_JOINS_AND_CORNERS("MS_CJC_BUTT");
  public final static MS_CAPS_JOINS_AND_CORNERS MS_CJC_MITER = new MS_CAPS_JOINS_AND_CORNERS("MS_CJC_MITER");
  public final static MS_CAPS_JOINS_AND_CORNERS MS_CJC_ROUND = new MS_CAPS_JOINS_AND_CORNERS("MS_CJC_ROUND");
  public final static MS_CAPS_JOINS_AND_CORNERS MS_CJC_SQUARE = new MS_CAPS_JOINS_AND_CORNERS("MS_CJC_SQUARE");
  public final static MS_CAPS_JOINS_AND_CORNERS MS_CJC_TRIANGLE = new MS_CAPS_JOINS_AND_CORNERS("MS_CJC_TRIANGLE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static MS_CAPS_JOINS_AND_CORNERS swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + MS_CAPS_JOINS_AND_CORNERS.class + " with value " + swigValue);
  }

  private MS_CAPS_JOINS_AND_CORNERS(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private MS_CAPS_JOINS_AND_CORNERS(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue + 1;
  }

  private MS_CAPS_JOINS_AND_CORNERS(String swigName, MS_CAPS_JOINS_AND_CORNERS swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue + 1;
  }

  private static MS_CAPS_JOINS_AND_CORNERS[] swigValues = { MS_CJC_NONE, MS_CJC_BEVEL, MS_CJC_BUTT, MS_CJC_MITER,
      MS_CJC_ROUND, MS_CJC_SQUARE, MS_CJC_TRIANGLE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}
