package edu.umn.gis;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

public final class MS_POSITIONS_ENUM {
  public final static MS_POSITIONS_ENUM MS_UL = new MS_POSITIONS_ENUM("MS_UL", mapscriptJNI.MS_UL_get());
  public final static MS_POSITIONS_ENUM MS_LR = new MS_POSITIONS_ENUM("MS_LR");
  public final static MS_POSITIONS_ENUM MS_UR = new MS_POSITIONS_ENUM("MS_UR");
  public final static MS_POSITIONS_ENUM MS_LL = new MS_POSITIONS_ENUM("MS_LL");
  public final static MS_POSITIONS_ENUM MS_CR = new MS_POSITIONS_ENUM("MS_CR");
  public final static MS_POSITIONS_ENUM MS_CL = new MS_POSITIONS_ENUM("MS_CL");
  public final static MS_POSITIONS_ENUM MS_UC = new MS_POSITIONS_ENUM("MS_UC");
  public final static MS_POSITIONS_ENUM MS_LC = new MS_POSITIONS_ENUM("MS_LC");
  public final static MS_POSITIONS_ENUM MS_CC = new MS_POSITIONS_ENUM("MS_CC");
  public final static MS_POSITIONS_ENUM MS_AUTO = new MS_POSITIONS_ENUM("MS_AUTO");
  public final static MS_POSITIONS_ENUM MS_XY = new MS_POSITIONS_ENUM("MS_XY");
  public final static MS_POSITIONS_ENUM MS_FOLLOW = new MS_POSITIONS_ENUM("MS_FOLLOW");
  public final static MS_POSITIONS_ENUM MS_NONE = new MS_POSITIONS_ENUM("MS_NONE");
  public final static MS_POSITIONS_ENUM MS_AUTO2 = new MS_POSITIONS_ENUM("MS_AUTO2");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static MS_POSITIONS_ENUM swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + MS_POSITIONS_ENUM.class + " with value " + swigValue);
  }

  private MS_POSITIONS_ENUM(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private MS_POSITIONS_ENUM(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue + 1;
  }

  private MS_POSITIONS_ENUM(String swigName, MS_POSITIONS_ENUM swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue + 1;
  }

  private static MS_POSITIONS_ENUM[] swigValues = { MS_UL, MS_LR, MS_UR, MS_LL, MS_CR, MS_CL, MS_UC, MS_LC, MS_CC,
      MS_AUTO, MS_XY, MS_FOLLOW, MS_NONE, MS_AUTO2 };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}
