package edu.umn.gis;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

public final class MS_QUERY_MODE {
  public final static MS_QUERY_MODE MS_QUERY_SINGLE = new MS_QUERY_MODE("MS_QUERY_SINGLE");
  public final static MS_QUERY_MODE MS_QUERY_MULTIPLE = new MS_QUERY_MODE("MS_QUERY_MULTIPLE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static MS_QUERY_MODE swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + MS_QUERY_MODE.class + " with value " + swigValue);
  }

  private MS_QUERY_MODE(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private MS_QUERY_MODE(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue + 1;
  }

  private MS_QUERY_MODE(String swigName, MS_QUERY_MODE swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue + 1;
  }

  private static MS_QUERY_MODE[] swigValues = { MS_QUERY_SINGLE, MS_QUERY_MULTIPLE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}
