package edu.umn.gis;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

public final class MS_STYLE_BINDING_ENUM {
  public final static MS_STYLE_BINDING_ENUM MS_STYLE_BINDING_SIZE = new MS_STYLE_BINDING_ENUM("MS_STYLE_BINDING_SIZE");
  public final static MS_STYLE_BINDING_ENUM MS_STYLE_BINDING_WIDTH = new MS_STYLE_BINDING_ENUM(
      "MS_STYLE_BINDING_WIDTH");
  public final static MS_STYLE_BINDING_ENUM MS_STYLE_BINDING_ANGLE = new MS_STYLE_BINDING_ENUM(
      "MS_STYLE_BINDING_ANGLE");
  public final static MS_STYLE_BINDING_ENUM MS_STYLE_BINDING_COLOR = new MS_STYLE_BINDING_ENUM(
      "MS_STYLE_BINDING_COLOR");
  public final static MS_STYLE_BINDING_ENUM MS_STYLE_BINDING_OUTLINECOLOR = new MS_STYLE_BINDING_ENUM(
      "MS_STYLE_BINDING_OUTLINECOLOR");
  public final static MS_STYLE_BINDING_ENUM MS_STYLE_BINDING_SYMBOL = new MS_STYLE_BINDING_ENUM(
      "MS_STYLE_BINDING_SYMBOL");
  public final static MS_STYLE_BINDING_ENUM MS_STYLE_BINDING_OUTLINEWIDTH = new MS_STYLE_BINDING_ENUM(
      "MS_STYLE_BINDING_OUTLINEWIDTH");
  public final static MS_STYLE_BINDING_ENUM MS_STYLE_BINDING_OPACITY = new MS_STYLE_BINDING_ENUM(
      "MS_STYLE_BINDING_OPACITY");
  public final static MS_STYLE_BINDING_ENUM MS_STYLE_BINDING_OFFSET_X = new MS_STYLE_BINDING_ENUM(
      "MS_STYLE_BINDING_OFFSET_X");
  public final static MS_STYLE_BINDING_ENUM MS_STYLE_BINDING_OFFSET_Y = new MS_STYLE_BINDING_ENUM(
      "MS_STYLE_BINDING_OFFSET_Y");
  public final static MS_STYLE_BINDING_ENUM MS_STYLE_BINDING_POLAROFFSET_PIXEL = new MS_STYLE_BINDING_ENUM(
      "MS_STYLE_BINDING_POLAROFFSET_PIXEL");
  public final static MS_STYLE_BINDING_ENUM MS_STYLE_BINDING_POLAROFFSET_ANGLE = new MS_STYLE_BINDING_ENUM(
      "MS_STYLE_BINDING_POLAROFFSET_ANGLE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static MS_STYLE_BINDING_ENUM swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + MS_STYLE_BINDING_ENUM.class + " with value " + swigValue);
  }

  private MS_STYLE_BINDING_ENUM(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private MS_STYLE_BINDING_ENUM(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue + 1;
  }

  private MS_STYLE_BINDING_ENUM(String swigName, MS_STYLE_BINDING_ENUM swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue + 1;
  }

  private static MS_STYLE_BINDING_ENUM[] swigValues = { MS_STYLE_BINDING_SIZE, MS_STYLE_BINDING_WIDTH,
      MS_STYLE_BINDING_ANGLE, MS_STYLE_BINDING_COLOR, MS_STYLE_BINDING_OUTLINECOLOR, MS_STYLE_BINDING_SYMBOL,
      MS_STYLE_BINDING_OUTLINEWIDTH, MS_STYLE_BINDING_OPACITY, MS_STYLE_BINDING_OFFSET_X, MS_STYLE_BINDING_OFFSET_Y,
      MS_STYLE_BINDING_POLAROFFSET_PIXEL, MS_STYLE_BINDING_POLAROFFSET_ANGLE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}
