package edu.umn.gis;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

public final class MS_TOKEN_COMPARISON_ENUM {
  public final static MS_TOKEN_COMPARISON_ENUM MS_TOKEN_COMPARISON_EQ = new MS_TOKEN_COMPARISON_ENUM(
      "MS_TOKEN_COMPARISON_EQ", mapscriptJNI.MS_TOKEN_COMPARISON_EQ_get());
  public final static MS_TOKEN_COMPARISON_ENUM MS_TOKEN_COMPARISON_NE = new MS_TOKEN_COMPARISON_ENUM(
      "MS_TOKEN_COMPARISON_NE");
  public final static MS_TOKEN_COMPARISON_ENUM MS_TOKEN_COMPARISON_GT = new MS_TOKEN_COMPARISON_ENUM(
      "MS_TOKEN_COMPARISON_GT");
  public final static MS_TOKEN_COMPARISON_ENUM MS_TOKEN_COMPARISON_LT = new MS_TOKEN_COMPARISON_ENUM(
      "MS_TOKEN_COMPARISON_LT");
  public final static MS_TOKEN_COMPARISON_ENUM MS_TOKEN_COMPARISON_LE = new MS_TOKEN_COMPARISON_ENUM(
      "MS_TOKEN_COMPARISON_LE");
  public final static MS_TOKEN_COMPARISON_ENUM MS_TOKEN_COMPARISON_GE = new MS_TOKEN_COMPARISON_ENUM(
      "MS_TOKEN_COMPARISON_GE");
  public final static MS_TOKEN_COMPARISON_ENUM MS_TOKEN_COMPARISON_IEQ = new MS_TOKEN_COMPARISON_ENUM(
      "MS_TOKEN_COMPARISON_IEQ");
  public final static MS_TOKEN_COMPARISON_ENUM MS_TOKEN_COMPARISON_RE = new MS_TOKEN_COMPARISON_ENUM(
      "MS_TOKEN_COMPARISON_RE");
  public final static MS_TOKEN_COMPARISON_ENUM MS_TOKEN_COMPARISON_IRE = new MS_TOKEN_COMPARISON_ENUM(
      "MS_TOKEN_COMPARISON_IRE");
  public final static MS_TOKEN_COMPARISON_ENUM MS_TOKEN_COMPARISON_IN = new MS_TOKEN_COMPARISON_ENUM(
      "MS_TOKEN_COMPARISON_IN");
  public final static MS_TOKEN_COMPARISON_ENUM MS_TOKEN_COMPARISON_LIKE = new MS_TOKEN_COMPARISON_ENUM(
      "MS_TOKEN_COMPARISON_LIKE");
  public final static MS_TOKEN_COMPARISON_ENUM MS_TOKEN_COMPARISON_INTERSECTS = new MS_TOKEN_COMPARISON_ENUM(
      "MS_TOKEN_COMPARISON_INTERSECTS");
  public final static MS_TOKEN_COMPARISON_ENUM MS_TOKEN_COMPARISON_DISJOINT = new MS_TOKEN_COMPARISON_ENUM(
      "MS_TOKEN_COMPARISON_DISJOINT");
  public final static MS_TOKEN_COMPARISON_ENUM MS_TOKEN_COMPARISON_TOUCHES = new MS_TOKEN_COMPARISON_ENUM(
      "MS_TOKEN_COMPARISON_TOUCHES");
  public final static MS_TOKEN_COMPARISON_ENUM MS_TOKEN_COMPARISON_OVERLAPS = new MS_TOKEN_COMPARISON_ENUM(
      "MS_TOKEN_COMPARISON_OVERLAPS");
  public final static MS_TOKEN_COMPARISON_ENUM MS_TOKEN_COMPARISON_CROSSES = new MS_TOKEN_COMPARISON_ENUM(
      "MS_TOKEN_COMPARISON_CROSSES");
  public final static MS_TOKEN_COMPARISON_ENUM MS_TOKEN_COMPARISON_WITHIN = new MS_TOKEN_COMPARISON_ENUM(
      "MS_TOKEN_COMPARISON_WITHIN");
  public final static MS_TOKEN_COMPARISON_ENUM MS_TOKEN_COMPARISON_CONTAINS = new MS_TOKEN_COMPARISON_ENUM(
      "MS_TOKEN_COMPARISON_CONTAINS");
  public final static MS_TOKEN_COMPARISON_ENUM MS_TOKEN_COMPARISON_BEYOND = new MS_TOKEN_COMPARISON_ENUM(
      "MS_TOKEN_COMPARISON_BEYOND");
  public final static MS_TOKEN_COMPARISON_ENUM MS_TOKEN_COMPARISON_DWITHIN = new MS_TOKEN_COMPARISON_ENUM(
      "MS_TOKEN_COMPARISON_DWITHIN");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static MS_TOKEN_COMPARISON_ENUM swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + MS_TOKEN_COMPARISON_ENUM.class + " with value " + swigValue);
  }

  private MS_TOKEN_COMPARISON_ENUM(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private MS_TOKEN_COMPARISON_ENUM(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue + 1;
  }

  private MS_TOKEN_COMPARISON_ENUM(String swigName, MS_TOKEN_COMPARISON_ENUM swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue + 1;
  }

  private static MS_TOKEN_COMPARISON_ENUM[] swigValues = { MS_TOKEN_COMPARISON_EQ, MS_TOKEN_COMPARISON_NE,
      MS_TOKEN_COMPARISON_GT, MS_TOKEN_COMPARISON_LT, MS_TOKEN_COMPARISON_LE, MS_TOKEN_COMPARISON_GE,
      MS_TOKEN_COMPARISON_IEQ, MS_TOKEN_COMPARISON_RE, MS_TOKEN_COMPARISON_IRE, MS_TOKEN_COMPARISON_IN,
      MS_TOKEN_COMPARISON_LIKE, MS_TOKEN_COMPARISON_INTERSECTS, MS_TOKEN_COMPARISON_DISJOINT,
      MS_TOKEN_COMPARISON_TOUCHES, MS_TOKEN_COMPARISON_OVERLAPS, MS_TOKEN_COMPARISON_CROSSES,
      MS_TOKEN_COMPARISON_WITHIN, MS_TOKEN_COMPARISON_CONTAINS, MS_TOKEN_COMPARISON_BEYOND,
      MS_TOKEN_COMPARISON_DWITHIN };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}
