package edu.umn.gis;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

public final class MS_TOKEN_LITERAL_ENUM {
  public final static MS_TOKEN_LITERAL_ENUM MS_TOKEN_LITERAL_NUMBER = new MS_TOKEN_LITERAL_ENUM(
      "MS_TOKEN_LITERAL_NUMBER", mapscriptJNI.MS_TOKEN_LITERAL_NUMBER_get());
  public final static MS_TOKEN_LITERAL_ENUM MS_TOKEN_LITERAL_STRING = new MS_TOKEN_LITERAL_ENUM(
      "MS_TOKEN_LITERAL_STRING");
  public final static MS_TOKEN_LITERAL_ENUM MS_TOKEN_LITERAL_TIME = new MS_TOKEN_LITERAL_ENUM("MS_TOKEN_LITERAL_TIME");
  public final static MS_TOKEN_LITERAL_ENUM MS_TOKEN_LITERAL_SHAPE = new MS_TOKEN_LITERAL_ENUM(
      "MS_TOKEN_LITERAL_SHAPE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static MS_TOKEN_LITERAL_ENUM swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + MS_TOKEN_LITERAL_ENUM.class + " with value " + swigValue);
  }

  private MS_TOKEN_LITERAL_ENUM(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private MS_TOKEN_LITERAL_ENUM(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue + 1;
  }

  private MS_TOKEN_LITERAL_ENUM(String swigName, MS_TOKEN_LITERAL_ENUM swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue + 1;
  }

  private static MS_TOKEN_LITERAL_ENUM[] swigValues = { MS_TOKEN_LITERAL_NUMBER, MS_TOKEN_LITERAL_STRING,
      MS_TOKEN_LITERAL_TIME, MS_TOKEN_LITERAL_SHAPE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}
