package edu.umn.gis;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

public final class MS_TOKEN_FUNCTION_ENUM {
  public final static MS_TOKEN_FUNCTION_ENUM MS_TOKEN_FUNCTION_LENGTH = new MS_TOKEN_FUNCTION_ENUM(
      "MS_TOKEN_FUNCTION_LENGTH", mapscriptJNI.MS_TOKEN_FUNCTION_LENGTH_get());
  public final static MS_TOKEN_FUNCTION_ENUM MS_TOKEN_FUNCTION_TOSTRING = new MS_TOKEN_FUNCTION_ENUM(
      "MS_TOKEN_FUNCTION_TOSTRING");
  public final static MS_TOKEN_FUNCTION_ENUM MS_TOKEN_FUNCTION_COMMIFY = new MS_TOKEN_FUNCTION_ENUM(
      "MS_TOKEN_FUNCTION_COMMIFY");
  public final static MS_TOKEN_FUNCTION_ENUM MS_TOKEN_FUNCTION_AREA = new MS_TOKEN_FUNCTION_ENUM(
      "MS_TOKEN_FUNCTION_AREA");
  public final static MS_TOKEN_FUNCTION_ENUM MS_TOKEN_FUNCTION_ROUND = new MS_TOKEN_FUNCTION_ENUM(
      "MS_TOKEN_FUNCTION_ROUND");
  public final static MS_TOKEN_FUNCTION_ENUM MS_TOKEN_FUNCTION_FROMTEXT = new MS_TOKEN_FUNCTION_ENUM(
      "MS_TOKEN_FUNCTION_FROMTEXT");
  public final static MS_TOKEN_FUNCTION_ENUM MS_TOKEN_FUNCTION_BUFFER = new MS_TOKEN_FUNCTION_ENUM(
      "MS_TOKEN_FUNCTION_BUFFER");
  public final static MS_TOKEN_FUNCTION_ENUM MS_TOKEN_FUNCTION_DIFFERENCE = new MS_TOKEN_FUNCTION_ENUM(
      "MS_TOKEN_FUNCTION_DIFFERENCE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static MS_TOKEN_FUNCTION_ENUM swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + MS_TOKEN_FUNCTION_ENUM.class + " with value " + swigValue);
  }

  private MS_TOKEN_FUNCTION_ENUM(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private MS_TOKEN_FUNCTION_ENUM(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue + 1;
  }

  private MS_TOKEN_FUNCTION_ENUM(String swigName, MS_TOKEN_FUNCTION_ENUM swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue + 1;
  }

  private static MS_TOKEN_FUNCTION_ENUM[] swigValues = { MS_TOKEN_FUNCTION_LENGTH, MS_TOKEN_FUNCTION_TOSTRING,
      MS_TOKEN_FUNCTION_COMMIFY, MS_TOKEN_FUNCTION_AREA, MS_TOKEN_FUNCTION_ROUND, MS_TOKEN_FUNCTION_FROMTEXT,
      MS_TOKEN_FUNCTION_BUFFER, MS_TOKEN_FUNCTION_DIFFERENCE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}
