package edu.umn.gis;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

public final class MS_UNITS {
  public final static MS_UNITS MS_INCHES = new MS_UNITS("MS_INCHES");
  public final static MS_UNITS MS_FEET = new MS_UNITS("MS_FEET");
  public final static MS_UNITS MS_MILES = new MS_UNITS("MS_MILES");
  public final static MS_UNITS MS_METERS = new MS_UNITS("MS_METERS");
  public final static MS_UNITS MS_KILOMETERS = new MS_UNITS("MS_KILOMETERS");
  public final static MS_UNITS MS_DD = new MS_UNITS("MS_DD");
  public final static MS_UNITS MS_PIXELS = new MS_UNITS("MS_PIXELS");
  public final static MS_UNITS MS_PERCENTAGES = new MS_UNITS("MS_PERCENTAGES");
  public final static MS_UNITS MS_NAUTICALMILES = new MS_UNITS("MS_NAUTICALMILES");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static MS_UNITS swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + MS_UNITS.class + " with value " + swigValue);
  }

  private MS_UNITS(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private MS_UNITS(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue + 1;
  }

  private MS_UNITS(String swigName, MS_UNITS swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue + 1;
  }

  private static MS_UNITS[] swigValues = { MS_INCHES, MS_FEET, MS_MILES, MS_METERS, MS_KILOMETERS, MS_DD, MS_PIXELS,
      MS_PERCENTAGES, MS_NAUTICALMILES };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}
