package edu.umn.gis;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

public class outputFormatObj {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected outputFormatObj(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(outputFormatObj obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mapscriptJNI.delete_outputFormatObj(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setName(String value) {
    mapscriptJNI.outputFormatObj_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return mapscriptJNI.outputFormatObj_name_get(swigCPtr, this);
  }

  public void setMimetype(String value) {
    mapscriptJNI.outputFormatObj_mimetype_set(swigCPtr, this, value);
  }

  public String getMimetype() {
    return mapscriptJNI.outputFormatObj_mimetype_get(swigCPtr, this);
  }

  public void setDriver(String value) {
    mapscriptJNI.outputFormatObj_driver_set(swigCPtr, this, value);
  }

  public String getDriver() {
    return mapscriptJNI.outputFormatObj_driver_get(swigCPtr, this);
  }

  public void setExtension(String value) {
    mapscriptJNI.outputFormatObj_extension_set(swigCPtr, this, value);
  }

  public String getExtension() {
    return mapscriptJNI.outputFormatObj_extension_get(swigCPtr, this);
  }

  public void setRenderer(int value) {
    mapscriptJNI.outputFormatObj_renderer_set(swigCPtr, this, value);
  }

  public int getRenderer() {
    return mapscriptJNI.outputFormatObj_renderer_get(swigCPtr, this);
  }

  public void setImagemode(int value) {
    mapscriptJNI.outputFormatObj_imagemode_set(swigCPtr, this, value);
  }

  public int getImagemode() {
    return mapscriptJNI.outputFormatObj_imagemode_get(swigCPtr, this);
  }

  public void setTransparent(int value) {
    mapscriptJNI.outputFormatObj_transparent_set(swigCPtr, this, value);
  }

  public int getTransparent() {
    return mapscriptJNI.outputFormatObj_transparent_get(swigCPtr, this);
  }

  public void setBands(int value) {
    mapscriptJNI.outputFormatObj_bands_set(swigCPtr, this, value);
  }

  public int getBands() {
    return mapscriptJNI.outputFormatObj_bands_get(swigCPtr, this);
  }

  public void setNumformatoptions(int value) {
    mapscriptJNI.outputFormatObj_numformatoptions_set(swigCPtr, this, value);
  }

  public int getNumformatoptions() {
    return mapscriptJNI.outputFormatObj_numformatoptions_get(swigCPtr, this);
  }

  public void setFormatoptions(SWIGTYPE_p_p_char value) {
    mapscriptJNI.outputFormatObj_formatoptions_set(swigCPtr, this, SWIGTYPE_p_p_char.getCPtr(value));
  }

  public SWIGTYPE_p_p_char getFormatoptions() {
    long cPtr = mapscriptJNI.outputFormatObj_formatoptions_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_char(cPtr, false);
  }

  public void setRefcount(int value) {
    mapscriptJNI.outputFormatObj_refcount_set(swigCPtr, this, value);
  }

  public int getRefcount() {
    return mapscriptJNI.outputFormatObj_refcount_get(swigCPtr, this);
  }

  public void setInmapfile(int value) {
    mapscriptJNI.outputFormatObj_inmapfile_set(swigCPtr, this, value);
  }

  public int getInmapfile() {
    return mapscriptJNI.outputFormatObj_inmapfile_get(swigCPtr, this);
  }

  public outputFormatObj(String driver, String name) {
    this(mapscriptJNI.new_outputFormatObj(driver, name), true);
  }

  public void setOption(String key, String value) {
    mapscriptJNI.outputFormatObj_setOption(swigCPtr, this, key, value);
  }

  public int validate() {
    return mapscriptJNI.outputFormatObj_validate(swigCPtr, this);
  }

  public String getOption(String key, String value) {
    return mapscriptJNI.outputFormatObj_getOption(swigCPtr, this, key, value);
  }

  public void attachDevice(SWIGTYPE_p_void device) {
    mapscriptJNI.outputFormatObj_attachDevice(swigCPtr, this, SWIGTYPE_p_void.getCPtr(device));
  }

}
