package edu.umn.gis;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

public class projectionObj {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected projectionObj(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(projectionObj obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mapscriptJNI.delete_projectionObj(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int getNumargs() {
    return mapscriptJNI.projectionObj_numargs_get(swigCPtr, this);
  }

  public int getAutomatic() {
    return mapscriptJNI.projectionObj_automatic_get(swigCPtr, this);
  }

  public projectionObj(String proj4) {
    this(mapscriptJNI.new_projectionObj(proj4), true);
  }

  public int setWKTProjection(String wkt) {
    return mapscriptJNI.projectionObj_setWKTProjection(swigCPtr, this, wkt);
  }

  public int getUnits() {
    return mapscriptJNI.projectionObj_getUnits(swigCPtr, this);
  }

}
