package edu.umn.gis;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

public class queryMapObj {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected queryMapObj(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(queryMapObj obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mapscriptJNI.delete_queryMapObj(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setHeight(int value) {
    mapscriptJNI.queryMapObj_height_set(swigCPtr, this, value);
  }

  public int getHeight() {
    return mapscriptJNI.queryMapObj_height_get(swigCPtr, this);
  }

  public void setWidth(int value) {
    mapscriptJNI.queryMapObj_width_set(swigCPtr, this, value);
  }

  public int getWidth() {
    return mapscriptJNI.queryMapObj_width_get(swigCPtr, this);
  }

  public void setStatus(int value) {
    mapscriptJNI.queryMapObj_status_set(swigCPtr, this, value);
  }

  public int getStatus() {
    return mapscriptJNI.queryMapObj_status_get(swigCPtr, this);
  }

  public void setStyle(int value) {
    mapscriptJNI.queryMapObj_style_set(swigCPtr, this, value);
  }

  public int getStyle() {
    return mapscriptJNI.queryMapObj_style_get(swigCPtr, this);
  }

  public void setColor(colorObj value) {
    mapscriptJNI.queryMapObj_color_set(swigCPtr, this, colorObj.getCPtr(value), value);
  }

  public colorObj getColor() {
    long cPtr = mapscriptJNI.queryMapObj_color_get(swigCPtr, this);
    return (cPtr == 0) ? null : new colorObj(cPtr, false);
  }

  public int updateFromString(String snippet) {
    return mapscriptJNI.queryMapObj_updateFromString(swigCPtr, this, snippet);
  }

  public queryMapObj() {
    this(mapscriptJNI.new_queryMapObj(), true);
  }

}
