package edu.umn.gis;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

public class symbolStyleObj {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected symbolStyleObj(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(symbolStyleObj obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mapscriptJNI.delete_symbolStyleObj(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setColor(colorObj value) {
    mapscriptJNI.symbolStyleObj_color_set(swigCPtr, this, colorObj.getCPtr(value), value);
  }

  public colorObj getColor() {
    long cPtr = mapscriptJNI.symbolStyleObj_color_get(swigCPtr, this);
    return (cPtr == 0) ? null : new colorObj(cPtr, false);
  }

  public void setBackgroundcolor(colorObj value) {
    mapscriptJNI.symbolStyleObj_backgroundcolor_set(swigCPtr, this, colorObj.getCPtr(value), value);
  }

  public colorObj getBackgroundcolor() {
    long cPtr = mapscriptJNI.symbolStyleObj_backgroundcolor_get(swigCPtr, this);
    return (cPtr == 0) ? null : new colorObj(cPtr, false);
  }

  public void setOutlinewidth(double value) {
    mapscriptJNI.symbolStyleObj_outlinewidth_set(swigCPtr, this, value);
  }

  public double getOutlinewidth() {
    return mapscriptJNI.symbolStyleObj_outlinewidth_get(swigCPtr, this);
  }

  public void setOutlinecolor(colorObj value) {
    mapscriptJNI.symbolStyleObj_outlinecolor_set(swigCPtr, this, colorObj.getCPtr(value), value);
  }

  public colorObj getOutlinecolor() {
    long cPtr = mapscriptJNI.symbolStyleObj_outlinecolor_get(swigCPtr, this);
    return (cPtr == 0) ? null : new colorObj(cPtr, false);
  }

  public void setScale(double value) {
    mapscriptJNI.symbolStyleObj_scale_set(swigCPtr, this, value);
  }

  public double getScale() {
    return mapscriptJNI.symbolStyleObj_scale_get(swigCPtr, this);
  }

  public void setRotation(double value) {
    mapscriptJNI.symbolStyleObj_rotation_set(swigCPtr, this, value);
  }

  public double getRotation() {
    return mapscriptJNI.symbolStyleObj_rotation_get(swigCPtr, this);
  }

  public void setGap(double value) {
    mapscriptJNI.symbolStyleObj_gap_set(swigCPtr, this, value);
  }

  public double getGap() {
    return mapscriptJNI.symbolStyleObj_gap_get(swigCPtr, this);
  }

  public void setStyle(styleObj value) {
    mapscriptJNI.symbolStyleObj_style_set(swigCPtr, this, styleObj.getCPtr(value), value);
  }

  public styleObj getStyle() {
    long cPtr = mapscriptJNI.symbolStyleObj_style_get(swigCPtr, this);
    return (cPtr == 0) ? null : new styleObj(cPtr, false);
  }

  public symbolStyleObj() {
    this(mapscriptJNI.new_symbolStyleObj(), true);
  }

}
