package edu.umn.gis;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

public class symbolObj {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected symbolObj(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(symbolObj obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mapscriptJNI.delete_symbolObj(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setName(String value) {
    mapscriptJNI.symbolObj_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return mapscriptJNI.symbolObj_name_get(swigCPtr, this);
  }

  public void setType(int value) {
    mapscriptJNI.symbolObj_type_set(swigCPtr, this, value);
  }

  public int getType() {
    return mapscriptJNI.symbolObj_type_get(swigCPtr, this);
  }

  public void setInmapfile(int value) {
    mapscriptJNI.symbolObj_inmapfile_set(swigCPtr, this, value);
  }

  public int getInmapfile() {
    return mapscriptJNI.symbolObj_inmapfile_get(swigCPtr, this);
  }

  public void setSizex(double value) {
    mapscriptJNI.symbolObj_sizex_set(swigCPtr, this, value);
  }

  public double getSizex() {
    return mapscriptJNI.symbolObj_sizex_get(swigCPtr, this);
  }

  public void setSizey(double value) {
    mapscriptJNI.symbolObj_sizey_set(swigCPtr, this, value);
  }

  public double getSizey() {
    return mapscriptJNI.symbolObj_sizey_get(swigCPtr, this);
  }

  public void setMinx(double value) {
    mapscriptJNI.symbolObj_minx_set(swigCPtr, this, value);
  }

  public double getMinx() {
    return mapscriptJNI.symbolObj_minx_get(swigCPtr, this);
  }

  public void setMiny(double value) {
    mapscriptJNI.symbolObj_miny_set(swigCPtr, this, value);
  }

  public double getMiny() {
    return mapscriptJNI.symbolObj_miny_get(swigCPtr, this);
  }

  public void setMaxx(double value) {
    mapscriptJNI.symbolObj_maxx_set(swigCPtr, this, value);
  }

  public double getMaxx() {
    return mapscriptJNI.symbolObj_maxx_get(swigCPtr, this);
  }

  public void setMaxy(double value) {
    mapscriptJNI.symbolObj_maxy_set(swigCPtr, this, value);
  }

  public double getMaxy() {
    return mapscriptJNI.symbolObj_maxy_get(swigCPtr, this);
  }

  public int getRefcount() {
    return mapscriptJNI.symbolObj_refcount_get(swigCPtr, this);
  }

  public int getNumpoints() {
    return mapscriptJNI.symbolObj_numpoints_get(swigCPtr, this);
  }

  public void setFilled(int value) {
    mapscriptJNI.symbolObj_filled_set(swigCPtr, this, value);
  }

  public int getFilled() {
    return mapscriptJNI.symbolObj_filled_get(swigCPtr, this);
  }

  public void setAnchorpoint_x(double value) {
    mapscriptJNI.symbolObj_anchorpoint_x_set(swigCPtr, this, value);
  }

  public double getAnchorpoint_x() {
    return mapscriptJNI.symbolObj_anchorpoint_x_get(swigCPtr, this);
  }

  public void setAnchorpoint_y(double value) {
    mapscriptJNI.symbolObj_anchorpoint_y_set(swigCPtr, this, value);
  }

  public double getAnchorpoint_y() {
    return mapscriptJNI.symbolObj_anchorpoint_y_get(swigCPtr, this);
  }

  public String getImagepath() {
    return mapscriptJNI.symbolObj_imagepath_get(swigCPtr, this);
  }

  public void setTransparent(int value) {
    mapscriptJNI.symbolObj_transparent_set(swigCPtr, this, value);
  }

  public int getTransparent() {
    return mapscriptJNI.symbolObj_transparent_get(swigCPtr, this);
  }

  public void setTransparentcolor(int value) {
    mapscriptJNI.symbolObj_transparentcolor_set(swigCPtr, this, value);
  }

  public int getTransparentcolor() {
    return mapscriptJNI.symbolObj_transparentcolor_get(swigCPtr, this);
  }

  public void setCharacter(String value) {
    mapscriptJNI.symbolObj_character_set(swigCPtr, this, value);
  }

  public String getCharacter() {
    return mapscriptJNI.symbolObj_character_get(swigCPtr, this);
  }

  public void setAntialias(int value) {
    mapscriptJNI.symbolObj_antialias_set(swigCPtr, this, value);
  }

  public int getAntialias() {
    return mapscriptJNI.symbolObj_antialias_get(swigCPtr, this);
  }

  public void setFont(String value) {
    mapscriptJNI.symbolObj_font_set(swigCPtr, this, value);
  }

  public String getFont() {
    return mapscriptJNI.symbolObj_font_get(swigCPtr, this);
  }

  public void setSvg_text(String value) {
    mapscriptJNI.symbolObj_svg_text_set(swigCPtr, this, value);
  }

  public String getSvg_text() {
    return mapscriptJNI.symbolObj_svg_text_get(swigCPtr, this);
  }

  public symbolObj(String symbolname, String imagefile) {
    this(mapscriptJNI.new_symbolObj(symbolname, imagefile), true);
  }

  public int setImagepath(String imagefile) {
    return mapscriptJNI.symbolObj_setImagepath(swigCPtr, this, imagefile);
  }

  public int setPoints(lineObj line) {
    return mapscriptJNI.symbolObj_setPoints(swigCPtr, this, lineObj.getCPtr(line), line);
  }

  public lineObj getPoints() {
    long cPtr = mapscriptJNI.symbolObj_getPoints(swigCPtr, this);
    return (cPtr == 0) ? null : new lineObj(cPtr, true);
  }

  public imageObj getImage(outputFormatObj input_format) {
    long cPtr = mapscriptJNI.symbolObj_getImage(swigCPtr, this, outputFormatObj.getCPtr(input_format), input_format);
    return (cPtr == 0) ? null : new imageObj(cPtr, true);
  }

  public int setImage(imageObj image) {
    return mapscriptJNI.symbolObj_setImage(swigCPtr, this, imageObj.getCPtr(image), image);
  }

}
