/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.umn.gis.mapscript;

public class clusterObj {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected clusterObj(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(clusterObj obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mapscriptJNI.delete_clusterObj(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMaxdistance(double value) {
    mapscriptJNI.clusterObj_maxdistance_set(swigCPtr, this, value);
  }

  public double getMaxdistance() {
    return mapscriptJNI.clusterObj_maxdistance_get(swigCPtr, this);
  }

  public void setBuffer(double value) {
    mapscriptJNI.clusterObj_buffer_set(swigCPtr, this, value);
  }

  public double getBuffer() {
    return mapscriptJNI.clusterObj_buffer_get(swigCPtr, this);
  }

  public void setRegion(String value) {
    mapscriptJNI.clusterObj_region_set(swigCPtr, this, value);
  }

  public String getRegion() {
    return mapscriptJNI.clusterObj_region_get(swigCPtr, this);
  }

  public int updateFromString(String snippet) {
    return mapscriptJNI.clusterObj_updateFromString(swigCPtr, this, snippet);
  }

  public String convertToString() {
    return mapscriptJNI.clusterObj_convertToString(swigCPtr, this);
  }

  public int setGroup(String group) {
    return mapscriptJNI.clusterObj_setGroup(swigCPtr, this, group);
  }

  public String getGroupString() {
    return mapscriptJNI.clusterObj_getGroupString(swigCPtr, this);
  }

  public int setFilter(String filter) {
    return mapscriptJNI.clusterObj_setFilter(swigCPtr, this, filter);
  }

  public String getFilterString() {
    return mapscriptJNI.clusterObj_getFilterString(swigCPtr, this);
  }

  public clusterObj() {
    this(mapscriptJNI.new_clusterObj(), true);
  }

}
