/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.umn.gis.mapscript;

public class configObj {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected configObj(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(configObj obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mapscriptJNI.delete_configObj(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setEnv(hashTableObj value) {
    mapscriptJNI.configObj_env_set(swigCPtr, this, hashTableObj.getCPtr(value), value);
  }

  public hashTableObj getEnv() {
    long cPtr = mapscriptJNI.configObj_env_get(swigCPtr, this);
    return (cPtr == 0) ? null : new hashTableObj(cPtr, false);
  }

  public void setMaps(hashTableObj value) {
    mapscriptJNI.configObj_maps_set(swigCPtr, this, hashTableObj.getCPtr(value), value);
  }

  public hashTableObj getMaps() {
    long cPtr = mapscriptJNI.configObj_maps_get(swigCPtr, this);
    return (cPtr == 0) ? null : new hashTableObj(cPtr, false);
  }

  public void setPlugins(hashTableObj value) {
    mapscriptJNI.configObj_plugins_set(swigCPtr, this, hashTableObj.getCPtr(value), value);
  }

  public hashTableObj getPlugins() {
    long cPtr = mapscriptJNI.configObj_plugins_get(swigCPtr, this);
    return (cPtr == 0) ? null : new hashTableObj(cPtr, false);
  }

  public configObj(String filename) {
    this(mapscriptJNI.new_configObj(filename), true);
  }

}
