/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.umn.gis.mapscript;

public class errorObj {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected errorObj(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(errorObj obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mapscriptJNI.delete_errorObj(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCode(int value) {
    mapscriptJNI.errorObj_code_set(swigCPtr, this, value);
  }

  public int getCode() {
    return mapscriptJNI.errorObj_code_get(swigCPtr, this);
  }

  public void setRoutine(String value) {
    mapscriptJNI.errorObj_routine_set(swigCPtr, this, value);
  }

  public String getRoutine() {
    return mapscriptJNI.errorObj_routine_get(swigCPtr, this);
  }

  public void setMessage(String value) {
    mapscriptJNI.errorObj_message_set(swigCPtr, this, value);
  }

  public String getMessage() {
    return mapscriptJNI.errorObj_message_get(swigCPtr, this);
  }

  public void setIsreported(int value) {
    mapscriptJNI.errorObj_isreported_set(swigCPtr, this, value);
  }

  public int getIsreported() {
    return mapscriptJNI.errorObj_isreported_get(swigCPtr, this);
  }

  public void setErrorcount(int value) {
    mapscriptJNI.errorObj_errorcount_set(swigCPtr, this, value);
  }

  public int getErrorcount() {
    return mapscriptJNI.errorObj_errorcount_get(swigCPtr, this);
  }

  public errorObj() {
    this(mapscriptJNI.new_errorObj(), true);
  }

  public errorObj next() {
    long cPtr = mapscriptJNI.errorObj_next(swigCPtr, this);
    return (cPtr == 0) ? null : new errorObj(cPtr, false);
  }

}
