/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.umn.gis.mapscript;

public class LayerCompositer {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected LayerCompositer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LayerCompositer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mapscriptJNI.delete_LayerCompositer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setComp_op(CompositingOperation value) {
    mapscriptJNI.LayerCompositer_comp_op_set(swigCPtr, this, value.swigValue());
  }

  public CompositingOperation getComp_op() {
    return CompositingOperation.swigToEnum(mapscriptJNI.LayerCompositer_comp_op_get(swigCPtr, this));
  }

  public void setOpacity(int value) {
    mapscriptJNI.LayerCompositer_opacity_set(swigCPtr, this, value);
  }

  public int getOpacity() {
    return mapscriptJNI.LayerCompositer_opacity_get(swigCPtr, this);
  }

  public void setFilter(CompositingFilter value) {
    mapscriptJNI.LayerCompositer_filter_set(swigCPtr, this, CompositingFilter.getCPtr(value), value);
  }

  public CompositingFilter getFilter() {
    long cPtr = mapscriptJNI.LayerCompositer_filter_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CompositingFilter(cPtr, false);
  }

  public void setNext(LayerCompositer value) {
    mapscriptJNI.LayerCompositer_next_set(swigCPtr, this, LayerCompositer.getCPtr(value), value);
  }

  public LayerCompositer getNext() {
    long cPtr = mapscriptJNI.LayerCompositer_next_get(swigCPtr, this);
    return (cPtr == 0) ? null : new LayerCompositer(cPtr, false);
  }

  public LayerCompositer() {
    this(mapscriptJNI.new_LayerCompositer(), true);
  }

}
