/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.umn.gis.mapscript;

public class markerCacheMemberObj {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected markerCacheMemberObj(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(markerCacheMemberObj obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mapscriptJNI.delete_markerCacheMemberObj(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int getId() {
    return mapscriptJNI.markerCacheMemberObj_id_get(swigCPtr, this);
  }

  public rectObj getBounds() {
    long cPtr = mapscriptJNI.markerCacheMemberObj_bounds_get(swigCPtr, this);
    return (cPtr == 0) ? null : new rectObj(cPtr, false);
  }

  public markerCacheMemberObj() {
    this(mapscriptJNI.new_markerCacheMemberObj(), true);
  }

}
