/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.umn.gis.mapscript;

public final class MS_LAYER_TYPE {
  public final static MS_LAYER_TYPE MS_LAYER_POINT = new MS_LAYER_TYPE("MS_LAYER_POINT");
  public final static MS_LAYER_TYPE MS_LAYER_LINE = new MS_LAYER_TYPE("MS_LAYER_LINE");
  public final static MS_LAYER_TYPE MS_LAYER_POLYGON = new MS_LAYER_TYPE("MS_LAYER_POLYGON");
  public final static MS_LAYER_TYPE MS_LAYER_RASTER = new MS_LAYER_TYPE("MS_LAYER_RASTER");
  public final static MS_LAYER_TYPE MS_LAYER_ANNOTATION = new MS_LAYER_TYPE("MS_LAYER_ANNOTATION");
  public final static MS_LAYER_TYPE MS_LAYER_QUERY = new MS_LAYER_TYPE("MS_LAYER_QUERY");
  public final static MS_LAYER_TYPE MS_LAYER_CIRCLE = new MS_LAYER_TYPE("MS_LAYER_CIRCLE");
  public final static MS_LAYER_TYPE MS_LAYER_TILEINDEX = new MS_LAYER_TYPE("MS_LAYER_TILEINDEX");
  public final static MS_LAYER_TYPE MS_LAYER_CHART = new MS_LAYER_TYPE("MS_LAYER_CHART");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static MS_LAYER_TYPE swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + MS_LAYER_TYPE.class + " with value " + swigValue);
  }

  private MS_LAYER_TYPE(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private MS_LAYER_TYPE(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private MS_LAYER_TYPE(String swigName, MS_LAYER_TYPE swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static MS_LAYER_TYPE[] swigValues = { MS_LAYER_POINT, MS_LAYER_LINE, MS_LAYER_POLYGON, MS_LAYER_RASTER, MS_LAYER_ANNOTATION, MS_LAYER_QUERY, MS_LAYER_CIRCLE, MS_LAYER_TILEINDEX, MS_LAYER_CHART };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

