/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.umn.gis.mapscript;

public final class MS_NUM_CHECK_TYPES {
  public final static MS_NUM_CHECK_TYPES MS_NUM_CHECK_NONE = new MS_NUM_CHECK_TYPES("MS_NUM_CHECK_NONE", mapscriptJNI.MS_NUM_CHECK_NONE_get());
  public final static MS_NUM_CHECK_TYPES MS_NUM_CHECK_RANGE = new MS_NUM_CHECK_TYPES("MS_NUM_CHECK_RANGE");
  public final static MS_NUM_CHECK_TYPES MS_NUM_CHECK_GT = new MS_NUM_CHECK_TYPES("MS_NUM_CHECK_GT");
  public final static MS_NUM_CHECK_TYPES MS_NUM_CHECK_GTE = new MS_NUM_CHECK_TYPES("MS_NUM_CHECK_GTE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static MS_NUM_CHECK_TYPES swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + MS_NUM_CHECK_TYPES.class + " with value " + swigValue);
  }

  private MS_NUM_CHECK_TYPES(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private MS_NUM_CHECK_TYPES(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private MS_NUM_CHECK_TYPES(String swigName, MS_NUM_CHECK_TYPES swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static MS_NUM_CHECK_TYPES[] swigValues = { MS_NUM_CHECK_NONE, MS_NUM_CHECK_RANGE, MS_NUM_CHECK_GT, MS_NUM_CHECK_GTE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

