/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.umn.gis.mapscript;

public final class MS_QUERYMAP_STYLES {
  public final static MS_QUERYMAP_STYLES MS_NORMAL = new MS_QUERYMAP_STYLES("MS_NORMAL");
  public final static MS_QUERYMAP_STYLES MS_HILITE = new MS_QUERYMAP_STYLES("MS_HILITE");
  public final static MS_QUERYMAP_STYLES MS_SELECTED = new MS_QUERYMAP_STYLES("MS_SELECTED");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static MS_QUERYMAP_STYLES swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + MS_QUERYMAP_STYLES.class + " with value " + swigValue);
  }

  private MS_QUERYMAP_STYLES(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private MS_QUERYMAP_STYLES(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private MS_QUERYMAP_STYLES(String swigName, MS_QUERYMAP_STYLES swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static MS_QUERYMAP_STYLES[] swigValues = { MS_NORMAL, MS_HILITE, MS_SELECTED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

