/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.umn.gis.mapscript;

public final class MS_RETURN_VALUE {
  public final static MS_RETURN_VALUE MS_SUCCESS = new MS_RETURN_VALUE("MS_SUCCESS");
  public final static MS_RETURN_VALUE MS_FAILURE = new MS_RETURN_VALUE("MS_FAILURE");
  public final static MS_RETURN_VALUE MS_DONE = new MS_RETURN_VALUE("MS_DONE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static MS_RETURN_VALUE swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + MS_RETURN_VALUE.class + " with value " + swigValue);
  }

  private MS_RETURN_VALUE(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private MS_RETURN_VALUE(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private MS_RETURN_VALUE(String swigName, MS_RETURN_VALUE swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static MS_RETURN_VALUE[] swigValues = { MS_SUCCESS, MS_FAILURE, MS_DONE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

