/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.umn.gis.mapscript;

public final class MS_TOKEN_LOGICAL_ENUM {
  public final static MS_TOKEN_LOGICAL_ENUM MS_TOKEN_LOGICAL_AND = new MS_TOKEN_LOGICAL_ENUM("MS_TOKEN_LOGICAL_AND", mapscriptJNI.MS_TOKEN_LOGICAL_AND_get());
  public final static MS_TOKEN_LOGICAL_ENUM MS_TOKEN_LOGICAL_OR = new MS_TOKEN_LOGICAL_ENUM("MS_TOKEN_LOGICAL_OR");
  public final static MS_TOKEN_LOGICAL_ENUM MS_TOKEN_LOGICAL_NOT = new MS_TOKEN_LOGICAL_ENUM("MS_TOKEN_LOGICAL_NOT");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static MS_TOKEN_LOGICAL_ENUM swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + MS_TOKEN_LOGICAL_ENUM.class + " with value " + swigValue);
  }

  private MS_TOKEN_LOGICAL_ENUM(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private MS_TOKEN_LOGICAL_ENUM(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private MS_TOKEN_LOGICAL_ENUM(String swigName, MS_TOKEN_LOGICAL_ENUM swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static MS_TOKEN_LOGICAL_ENUM[] swigValues = { MS_TOKEN_LOGICAL_AND, MS_TOKEN_LOGICAL_OR, MS_TOKEN_LOGICAL_NOT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

