/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.umn.gis.mapscript;

public final class MS_TRANSFORM_MODE {
  public final static MS_TRANSFORM_MODE MS_TRANSFORM_NONE = new MS_TRANSFORM_MODE("MS_TRANSFORM_NONE");
  public final static MS_TRANSFORM_MODE MS_TRANSFORM_ROUND = new MS_TRANSFORM_MODE("MS_TRANSFORM_ROUND");
  public final static MS_TRANSFORM_MODE MS_TRANSFORM_SNAPTOGRID = new MS_TRANSFORM_MODE("MS_TRANSFORM_SNAPTOGRID");
  public final static MS_TRANSFORM_MODE MS_TRANSFORM_FULLRESOLUTION = new MS_TRANSFORM_MODE("MS_TRANSFORM_FULLRESOLUTION");
  public final static MS_TRANSFORM_MODE MS_TRANSFORM_SIMPLIFY = new MS_TRANSFORM_MODE("MS_TRANSFORM_SIMPLIFY");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static MS_TRANSFORM_MODE swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + MS_TRANSFORM_MODE.class + " with value " + swigValue);
  }

  private MS_TRANSFORM_MODE(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private MS_TRANSFORM_MODE(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private MS_TRANSFORM_MODE(String swigName, MS_TRANSFORM_MODE swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static MS_TRANSFORM_MODE[] swigValues = { MS_TRANSFORM_NONE, MS_TRANSFORM_ROUND, MS_TRANSFORM_SNAPTOGRID, MS_TRANSFORM_FULLRESOLUTION, MS_TRANSFORM_SIMPLIFY };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

