/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.umn.gis.mapscript;

public class rectObj {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected rectObj(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(rectObj obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mapscriptJNI.delete_rectObj(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMinx(double value) {
    mapscriptJNI.rectObj_minx_set(swigCPtr, this, value);
  }

  public double getMinx() {
    return mapscriptJNI.rectObj_minx_get(swigCPtr, this);
  }

  public void setMiny(double value) {
    mapscriptJNI.rectObj_miny_set(swigCPtr, this, value);
  }

  public double getMiny() {
    return mapscriptJNI.rectObj_miny_get(swigCPtr, this);
  }

  public void setMaxx(double value) {
    mapscriptJNI.rectObj_maxx_set(swigCPtr, this, value);
  }

  public double getMaxx() {
    return mapscriptJNI.rectObj_maxx_get(swigCPtr, this);
  }

  public void setMaxy(double value) {
    mapscriptJNI.rectObj_maxy_set(swigCPtr, this, value);
  }

  public double getMaxy() {
    return mapscriptJNI.rectObj_maxy_get(swigCPtr, this);
  }

  public rectObj(double minx, double miny, double maxx, double maxy, int imageunits) {
    this(mapscriptJNI.new_rectObj(minx, miny, maxx, maxy, imageunits), true);
  }

  public int project(projectionObj projin, projectionObj projout) {
    return mapscriptJNI.rectObj_project__SWIG_0(swigCPtr, this, projectionObj.getCPtr(projin), projin, projectionObj.getCPtr(projout), projout);
  }

  public int project(reprojectionObj reprojector) {
    return mapscriptJNI.rectObj_project__SWIG_1(swigCPtr, this, reprojectionObj.getCPtr(reprojector), reprojector);
  }

  public double fit(int width, int height) {
    return mapscriptJNI.rectObj_fit(swigCPtr, this, width, height);
  }

  public int draw(mapObj map, layerObj layer, imageObj image, int classindex, String text) {
    return mapscriptJNI.rectObj_draw(swigCPtr, this, mapObj.getCPtr(map), map, layerObj.getCPtr(layer), layer, imageObj.getCPtr(image), image, classindex, text);
  }

  public pointObj getCenter() {
    long cPtr = mapscriptJNI.rectObj_getCenter(swigCPtr, this);
    return (cPtr == 0) ? null : new pointObj(cPtr, true);
  }

  public shapeObj toPolygon() {
    long cPtr = mapscriptJNI.rectObj_toPolygon(swigCPtr, this);
    return (cPtr == 0) ? null : new shapeObj(cPtr, true);
  }

  public String toString() {
    return mapscriptJNI.rectObj_toString(swigCPtr, this);
  }

}
