/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.umn.gis.mapscript;

public class resultCacheObj {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected resultCacheObj(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(resultCacheObj obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mapscriptJNI.delete_resultCacheObj(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int getNumresults() {
    return mapscriptJNI.resultCacheObj_numresults_get(swigCPtr, this);
  }

  public rectObj getBounds() {
    long cPtr = mapscriptJNI.resultCacheObj_bounds_get(swigCPtr, this);
    return (cPtr == 0) ? null : new rectObj(cPtr, false);
  }

  public resultObj getResult(int i) {
    long cPtr = mapscriptJNI.resultCacheObj_getResult(swigCPtr, this, i);
    return (cPtr == 0) ? null : new resultObj(cPtr, false);
  }

  public resultCacheObj() {
    this(mapscriptJNI.new_resultCacheObj(), true);
  }

}
