/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.umn.gis.mapscript;

public class scaleTokenEntryObj {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected scaleTokenEntryObj(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(scaleTokenEntryObj obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mapscriptJNI.delete_scaleTokenEntryObj(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMinscale(double value) {
    mapscriptJNI.scaleTokenEntryObj_minscale_set(swigCPtr, this, value);
  }

  public double getMinscale() {
    return mapscriptJNI.scaleTokenEntryObj_minscale_get(swigCPtr, this);
  }

  public void setMaxscale(double value) {
    mapscriptJNI.scaleTokenEntryObj_maxscale_set(swigCPtr, this, value);
  }

  public double getMaxscale() {
    return mapscriptJNI.scaleTokenEntryObj_maxscale_get(swigCPtr, this);
  }

  public void setValue(String value) {
    mapscriptJNI.scaleTokenEntryObj_value_set(swigCPtr, this, value);
  }

  public String getValue() {
    return mapscriptJNI.scaleTokenEntryObj_value_get(swigCPtr, this);
  }

  public scaleTokenEntryObj() {
    this(mapscriptJNI.new_scaleTokenEntryObj(), true);
  }

}
