/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.umn.gis.mapscript;

public class scalebarObj {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected scalebarObj(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(scalebarObj obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mapscriptJNI.delete_scalebarObj(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTransparent(int value) {
    mapscriptJNI.scalebarObj_transparent_set(swigCPtr, this, value);
  }

  public int getTransparent() {
    return mapscriptJNI.scalebarObj_transparent_get(swigCPtr, this);
  }

  public void setImagecolor(colorObj value) {
    mapscriptJNI.scalebarObj_imagecolor_set(swigCPtr, this, colorObj.getCPtr(value), value);
  }

  public colorObj getImagecolor() {
    long cPtr = mapscriptJNI.scalebarObj_imagecolor_get(swigCPtr, this);
    return (cPtr == 0) ? null : new colorObj(cPtr, false);
  }

  public void setHeight(int value) {
    mapscriptJNI.scalebarObj_height_set(swigCPtr, this, value);
  }

  public int getHeight() {
    return mapscriptJNI.scalebarObj_height_get(swigCPtr, this);
  }

  public void setWidth(int value) {
    mapscriptJNI.scalebarObj_width_set(swigCPtr, this, value);
  }

  public int getWidth() {
    return mapscriptJNI.scalebarObj_width_get(swigCPtr, this);
  }

  public void setStyle(int value) {
    mapscriptJNI.scalebarObj_style_set(swigCPtr, this, value);
  }

  public int getStyle() {
    return mapscriptJNI.scalebarObj_style_get(swigCPtr, this);
  }

  public void setIntervals(int value) {
    mapscriptJNI.scalebarObj_intervals_set(swigCPtr, this, value);
  }

  public int getIntervals() {
    return mapscriptJNI.scalebarObj_intervals_get(swigCPtr, this);
  }

  public void setLabel(labelObj value) {
    mapscriptJNI.scalebarObj_label_set(swigCPtr, this, labelObj.getCPtr(value), value);
  }

  public labelObj getLabel() {
    long cPtr = mapscriptJNI.scalebarObj_label_get(swigCPtr, this);
    return (cPtr == 0) ? null : new labelObj(cPtr, false);
  }

  public void setColor(colorObj value) {
    mapscriptJNI.scalebarObj_color_set(swigCPtr, this, colorObj.getCPtr(value), value);
  }

  public colorObj getColor() {
    long cPtr = mapscriptJNI.scalebarObj_color_get(swigCPtr, this);
    return (cPtr == 0) ? null : new colorObj(cPtr, false);
  }

  public void setBackgroundcolor(colorObj value) {
    mapscriptJNI.scalebarObj_backgroundcolor_set(swigCPtr, this, colorObj.getCPtr(value), value);
  }

  public colorObj getBackgroundcolor() {
    long cPtr = mapscriptJNI.scalebarObj_backgroundcolor_get(swigCPtr, this);
    return (cPtr == 0) ? null : new colorObj(cPtr, false);
  }

  public void setOutlinecolor(colorObj value) {
    mapscriptJNI.scalebarObj_outlinecolor_set(swigCPtr, this, colorObj.getCPtr(value), value);
  }

  public colorObj getOutlinecolor() {
    long cPtr = mapscriptJNI.scalebarObj_outlinecolor_get(swigCPtr, this);
    return (cPtr == 0) ? null : new colorObj(cPtr, false);
  }

  public void setUnits(int value) {
    mapscriptJNI.scalebarObj_units_set(swigCPtr, this, value);
  }

  public int getUnits() {
    return mapscriptJNI.scalebarObj_units_get(swigCPtr, this);
  }

  public void setStatus(int value) {
    mapscriptJNI.scalebarObj_status_set(swigCPtr, this, value);
  }

  public int getStatus() {
    return mapscriptJNI.scalebarObj_status_get(swigCPtr, this);
  }

  public void setPosition(int value) {
    mapscriptJNI.scalebarObj_position_set(swigCPtr, this, value);
  }

  public int getPosition() {
    return mapscriptJNI.scalebarObj_position_get(swigCPtr, this);
  }

  public void setPostlabelcache(int value) {
    mapscriptJNI.scalebarObj_postlabelcache_set(swigCPtr, this, value);
  }

  public int getPostlabelcache() {
    return mapscriptJNI.scalebarObj_postlabelcache_get(swigCPtr, this);
  }

  public void setAlign(int value) {
    mapscriptJNI.scalebarObj_align_set(swigCPtr, this, value);
  }

  public int getAlign() {
    return mapscriptJNI.scalebarObj_align_get(swigCPtr, this);
  }

  public void setOffsetx(int value) {
    mapscriptJNI.scalebarObj_offsetx_set(swigCPtr, this, value);
  }

  public int getOffsetx() {
    return mapscriptJNI.scalebarObj_offsetx_get(swigCPtr, this);
  }

  public void setOffsety(int value) {
    mapscriptJNI.scalebarObj_offsety_set(swigCPtr, this, value);
  }

  public int getOffsety() {
    return mapscriptJNI.scalebarObj_offsety_get(swigCPtr, this);
  }

  public int updateFromString(String snippet) {
    return mapscriptJNI.scalebarObj_updateFromString(swigCPtr, this, snippet);
  }

  public String convertToString() {
    return mapscriptJNI.scalebarObj_convertToString(swigCPtr, this);
  }

  public scalebarObj() {
    this(mapscriptJNI.new_scalebarObj(), true);
  }

}
